### ISSUE TITLE
Link's House Overhead View does not render correctly

### ISSUE THREAD

**Issue by MMurphy4096** [blawar/ooot#10]
Background for Link's House Overhead View does not render correctly
![image](https://user-images.githubusercontent.com/17395556/151916254-a6b09ed9-52ed-472c-bf84-0d35a7c77e2e.png)

**Comment by MMurphy4096** [comment]
Kokiri Shop also does not render its background correctly

![image](https://user-images.githubusercontent.com/17395556/151917381-a42549c3-a5fc-45c0-be8f-f7a703f2c17c.png)

**Comment by MatttyMattHew** [comment]
This is coming into the marketplace

![image](https://user-images.githubusercontent.com/98795913/151929947-bebfb009-2227-4369-9b75-dec95c8f69e8.png)

**Comment by MatttyMattHew** [comment]
In front of the temple of time

![image](https://user-images.githubusercontent.com/98795913/151930113-eab1eea3-05fa-44e9-868d-b7446ff4e180.png)

**Comment by blawar** [comment]
This should be fixed in master.  You will need to run convert_assets.py on master to re-extract the jpegs.
