### ISSUE TITLE
Hookshot does not attach to objects.

### ISSUE THREAD

**Issue by LilaHax** [blawar/ooot#101]
## Current Behavior
When using the hookshot it does not attach to any surface.

## Expected Behavior
Hookshot should attach to wooden surfaces and drag you across

## Steps to Reproduce
1. Create File 1 
2. Use debug menu to teleport to a location where you can use the hookshot
3. Equip and attempt to use the hookshot

https://user-images.githubusercontent.com/99148520/153322528-b16fd230-2792-4931-a5da-b3e6e5e74c56.mp4

**Comment by blawar** [comment]
fixed, re-run setup.py
