### ISSUE TITLE
missing asset link_animation.c

### ISSUE THREAD

**Issue by frizzle101101** [blawar/ooot#102]
![image](https://user-images.githubusercontent.com/11097522/153340444-12b54198-53a4-4b93-b8e5-2b041392b1a2.png)

there seems to be a missing extracted asset

**Comment by Zero3K** [comment]
Run setup.py.

**Comment by frizzle101101** [comment]
i have multiple times, its not showing up

**Comment by frizzle101101** [comment]
i just have a new clone

**Comment by Zero3K** [comment]
Did setup.py extract the assets, etc? Or do you not have the baserom_original.z64 in the root directory of the source code?

**Comment by blawar** [comment]
Did you run it from cmd.exe or did you use a linux environment to run it?

**Comment by frizzle101101** [comment]
I used linux environment and i have the same rom that i was using on
earlier commits

**Comment by Zero3K** [comment]
Please try building https://github.com/mrneo240/ooot-lite.

**Comment by frizzle101101** [comment]
so using the windows python seemed to work, does anyone know why using linux is broken now

**Comment by DaMarkov** [comment]
We are using fixed windows binary of ZAPD right now. So for linux you would have to build ZAPD yourself.
Is the building process working for you on windows?
