### ISSUE TITLE
Water current does not carry Link

### ISSUE THREAD

**Issue by Daniel6372** [blawar/ooot#107]
## Current Behavior

Link stays in place in the flowing water as if it was a stagnant body of water.
## Expected Behavior

Link should get carried by the current of the flowing water in the direction the current is flowing in.
## Steps to Reproduce

1. Create File 1
2. Use debug menu to select a location that has flowing water (e.g. Zora's River)
3. Get into the flowing body of water

**Comment by blawar** [comment]
This was fixed by #101 , please update and re-run setup.py
