### ISSUE TITLE
Weird Textures When The Camera is Showing Out of Bounds Areas

### ISSUE THREAD

**Issue by MatttyMattHew** [blawar/ooot#11]
Up against the wall in Kakariko, right when you go up the steps.

![image](https://user-images.githubusercontent.com/98795913/151916335-0d9c257b-a0b3-422d-adf2-f39cc328be8e.png)

**Comment by MMurphy4096** [comment]
Another example in the crawl tunnel in Kokiri Forest

![image](https://user-images.githubusercontent.com/17395556/151918253-fcc93484-c3b2-4e08-a6c0-4ec8724b25fb.png)

**Comment by blawar** [comment]
This is a known issue of GLideN64 when frame buffer emulation is disabled.  Should be fixed once frame buffer emulation is implemented.

**Comment by DaMarkov** [comment]
Can confirm that the second issue (crawl tunnel in Kokiri Forest) is fixed with frame buffer emulation.
I haven't tested the wall in Kakariko yet.

**Comment by Zero3K** [comment]
It has been fixed thanks to commit https://github.com/blawar/ooot/commit/ac2b25f6a5030a23867a68e989b104c2af11d340.
