### ISSUE TITLE
Certain rooms in Jabu Jabu's Belly don't show wall/floor/ceiling textures

### ISSUE THREAD

**Issue by Wesley107772** [blawar/ooot#114]
## Current Behavior
Should be a known issue, but posting it here for clarity
![image](https://user-images.githubusercontent.com/88684291/153544842-1b39e9fd-ba30-43aa-904e-deb6e56d704c.png)
![image](https://user-images.githubusercontent.com/88684291/153545104-72e7e847-a8f7-4129-a9d0-0ec6b06e0653.png)
![image](https://user-images.githubusercontent.com/88684291/153545172-fed48e72-135d-443c-8923-d70d08357e43.png)
![image](https://user-images.githubusercontent.com/88684291/153545723-a27a272f-3d5d-4a95-9bb4-524f67fefb23.png)
_(other weird issue in this one)_
etc

## Expected Behavior

![image](https://user-images.githubusercontent.com/88684291/153545230-577bb015-3092-4045-8aed-d0634c06c7af.png)
![image](https://user-images.githubusercontent.com/88684291/153545501-4fe31182-84bf-4d62-a6f2-2fe1419db919.png)
![image](https://user-images.githubusercontent.com/88684291/153545562-913245b3-16ed-406e-8ae5-3c1d2d7eba33.png)
![image](https://user-images.githubusercontent.com/88684291/153545793-bbaddc87-2857-457b-97b9-49289c61bb4d.png)

## Steps to Reproduce

Go to Jabu Jabu's Belly (maps 70 & 71)

**Comment by blawar** [comment]
run tools\fix_mtx.py
