### ISSUE TITLE
Upon entering Dampé's grave a second time, he does not appear at the start

### ISSUE THREAD

**Issue by Wesley107772** [blawar/ooot#115]
## Current Behavior

First time entering Dampé's grave everything is normal. You can talk to him, finish the race and get the reward. After that, however, he doesn't spawn again.
This can happen by finishing the race and coming back, by respawning due to falling/being crushed or even by immediately exiting his grave and going back in.
This persists until the game is restarted.

## Expected Behavior

Dampé should always appear and allow you to start the race.

## Steps to Reproduce

1. Enter Dampé's grave.
2. Leave.
3. Re-enter Dampé's grave.

https://user-images.githubusercontent.com/88684291/153555754-3c98a71c-1013-43da-acf6-e7af5f7f5a60.mp4

**Comment by DaMarkov** [comment]
Fixed in PR #120.
Thank you [Wesley107772](https://github.com/Wesley107772) for finding this bug
and [ajanhallinta](https://github.com/ajanhallinta) for your investigation.
