### ISSUE TITLE
Crash upon playing a second Ocarina song

### ISSUE THREAD

**Issue by Dewey-Wilkerson** [blawar/ooot#116]
## Current Behavior
Game crashes when you play a second song on the Ocarina

## Expected Behavior
The second song should "Play back" (no audio so no playback), and display on the screen

## Steps to Reproduce
1. Take out Ocarina
2. Play a song (Try Zelda's Lullaby, "C-Left C-Up C-Right" x2
3. Play a second song (Or Zelda's Lullaby again)
4. Crash

## Context (Environment)
Game breaking

https://user-images.githubusercontent.com/17395556/153572581-7a94a6cb-1654-4da3-9935-c52d9f2b3785.mp4

**Comment by blawar** [comment]
should be fixed.

**Comment by Wesley107772** [comment]
Possibly related to #123
