### ISSUE TITLE
No fadeout effect when entering houses

### ISSUE THREAD

**Issue by CYBER7R0N** [blawar/ooot#117]
## Current Behavior

![Capture](https://user-images.githubusercontent.com/99476373/153574164-6d5db574-2952-4f2c-b0ac-16b6c17cde8a.PNG)

## Expected Behavior

![Capture2](https://user-images.githubusercontent.com/99476373/153574216-b6da4275-651f-4474-b582-a2308da07e97.PNG)

## Steps to Reproduce

1. Enter house in Kakariko village
2.
3.
4.

**Comment by DaMarkov** [comment]
Fixed with the combined power of PR #112 and #165.
