### ISSUE TITLE
Saria is missing from the opening cutscene

### ISSUE THREAD

**Issue by CYBER7R0N** [blawar/ooot#118]
## Current Behavior

![image](https://user-images.githubusercontent.com/99476373/153579840-b4aa881a-ccbf-4cba-97ea-5de246d132c9.png)

## Steps to Reproduce

1. Start new game in save slot 2
2.
3.
4.

**Comment by Zero3K** [comment]
The developers already know of this issue.

**Comment by blawar** [comment]
fixed
