### ISSUE TITLE
Action icon does not show some actions

### ISSUE THREAD

**Issue by CYBER7R0N** [blawar/ooot#119]
## Current Behavior

![image](https://user-images.githubusercontent.com/99476373/153581421-301f156b-7f45-441a-8833-8020086359f8.png)

## Expected Behavior

![image](https://user-images.githubusercontent.com/99476373/153581553-baaa89fd-c24c-4573-ac0e-592fca230431.png)

## Steps to Reproduce

1.
2.
3.
4.

## Detailed Description

A button icon does not show "check" and "attack" while moving.

**Comment by DaMarkov** [comment]
Fixed in PR #175
