### ISSUE TITLE
HUD item equip animation is not scaled properly in widescreen

### ISSUE THREAD

**Issue by ajanhallinta** [blawar/ooot#121]
The animation in HUD, where an item "flies" to the C-button after equipping it on the Pause screen, is not scaled properly in widescreen mode.

## Current Behavior

The item flies to position, where the C-button icon would be in 4:3 aspect ratio, instead of the actual position of the C-button icon.

## Expected Behavior

Item should fly to position of pressed C-button icon.

## Steps to Reproduce

1. Equip an item on the Pause screen.

**Comment by blawar** [comment]
this is fixed in https://github.com/blawar/ooot/commit/7fdb2f2217f72bac9674d84577783e6b4046a5fe
