### ISSUE TITLE
Chickens in Zora's River do not appear after the first time

### ISSUE THREAD

**Issue by Wesley107772** [blawar/ooot#122]
## Current Behavior

After exiting and re-entering Zora's River as child Link, the two chickens do not reappear.
This persists until the game is restarted.

## Expected Behavior

The chickens should always be there as child Link.

## Possible Solution

Possibly similar issue to #115 ?

## Steps to Reproduce

1. Go to Zora's River as a child and verify that the chickens are there.
2. Exit Zora's River by any means.
3. Re-enter Zora's River and notice the missing chickens.

https://user-images.githubusercontent.com/88684291/153637000-925a0c48-1ddd-469d-b9cd-441c17837e5c.mp4

.

**Comment by ajanhallinta** [comment]
It seems that there is two booleans `sLowerRiverSpawned` and `sUpperRiverSpawned` in file `z_en_niw.c` that are set to true in `EnNiw_Init`, but they are never set back to false. If these booleans are true in `EnNiw_Init`, it will trigger killing those actors. Forcing them to be true in `EnNiw_Init` makes them to spawn again.

**Comment by mrneo240** [comment]
how levitate?

**Comment by Wesley107772** [comment]
> how levitate?

If you're asking about debug controls, here:
https://tcrf.net/Proto:The_Legend_of_Zelda:_Ocarina_of_Time_Master_Quest/General_Functions

**Comment by blawar** [comment]
fixed
