### ISSUE TITLE
Ocarina songs are much too slow

### ISSUE THREAD

**Issue by Wesley107772** [blawar/ooot#123]
## Current Behavior

The speed ocarina songs etc. are played at is much too slow, close to a third of the regular speed.
Comparisons can be seen in the video below.

## Expected Behavior

Songs should play at the same speed as on the N64.

## Steps to Reproduce

Play any song.
Or:
Spawn in the Forest Temple as adult Link and leave, to see the Minuet of Forest cutscene.
Then, compare it to the speed on the N64.

https://user-images.githubusercontent.com/88684291/153648576-f00734ae-95f9-4a1a-b371-b9c64de7d916.mp4

https://user-images.githubusercontent.com/88684291/153648845-0227bebf-f6b1-4b14-bb5c-acd7c0716354.mp4

**Comment by Wesley107772** [comment]
Still present in retail

**Comment by blawar** [comment]
can you verify this still exists on master?  I did not notice any audio delays.

**Comment by DaMarkov** [comment]
This is fixed now for Master Quest Debug.
