### ISSUE TITLE
No flying particles in Sacred Forest Meadow

### ISSUE THREAD

**Issue by Wesley107772** [blawar/ooot#124]
## Current Behavior

There are no flying particles in the Sacred Forest Meadow.
This happens both as child and adult Link.
See video for comparison.

## Expected Behavior

There should be flying particles in the Sacred Forest Meadow.

## Steps to Reproduce

1. Go to the Forest Temple.
2. Exit.
3. Compare N64 to PC Port results.

https://user-images.githubusercontent.com/88684291/153650206-afe8ecd3-41ed-4a9f-9d25-f93b375bbab5.mp4

**Comment by Zelllll** [comment]
I don't seem to have that issue.
![image](https://user-images.githubusercontent.com/56516451/153727012-241daae6-acca-4ffd-9696-929c5adf3824.png)

**Comment by ajanhallinta** [comment]
This might be another Actor Loading issue, as for me the particles are there when I entered first time, but they are gone if I exit the area and go back. By forcing `sIsSpawned` variable to be true in `z_object_kankyo.c` makes them appear always.

**Comment by Zero3K** [comment]
I can confirm that it has been fixed by the commit that was mentioned.
