### ISSUE TITLE
Game softlocks when dropping into the tiled floor room in the forest temple

### ISSUE THREAD

**Issue by LilaHax** [blawar/ooot#125]
## Current Behavior
When dropping into the tiled floor room in the forest temple the game crashes.

## Expected Behavior
You should be able to jump down and continue on into the dungeon.

## Steps to Reproduce
1. Create File 1
2. Play through the forest temple as normal
3. Attempt to jump down to the tiled floor room and the crash will happen.

(game freezes on this frame)
![image](https://user-images.githubusercontent.com/99148520/153668679-a771e5ff-05f2-40a9-9cd4-a9a1b20501b1.png)

**Comment by Wesley107772** [comment]
Debug output upon triggering this:

←[32mOVL(a):Seg:05e61fb0-05e61fb1 Ram:00000001-00000002 Off:05e61faf En_St
←[m←[32mOVL(a):Seg:05e620c4-05e620c5 Ram:00000001-00000002 Off:05e620c3 Bg_Mori_Rakkatenjo
←[m森の神殿 obj. 落下天井 (home posY 683.000000)
Warning : セット Angle が変更されています。プログラムを修正しましょう。
pp=1e0fde9c data=1.000000
←[32mDynaPolyInfo_setActor():index 2
←[m←[32mOVL(a):Seg:05e61f18-05e61f19 Ram:00000001-00000002 Off:05e61f17 En_Box
←[m←[32mDynaPolyInfo_setActor():index 3
←[m←[36m
エルフ タグ 消える条件 9←[m
←[36m
thisx->shape.angle.sy = 44
←[mpp=16a8d424 data=1.000000
←[32mOVL(a):Seg:05e62310-05e62311 Ram:00000001-00000002 Off:05e6230f Obj_Switch
←[m←[32mDynaPolyInfo_setActor():index 4
←[mpp=16edc9bc data=0.100000
(Dungeon switch)(arg_data 0x0e00)
←[32mDynaPolyInfo_setActor():index 5
←[mpp=16edcc44 data=0.100000
(Dungeon switch)(arg_data 0x1900)
←[31mDynaPolyInfo_expandSRT():polygon over do not use if 520 exceeds 512
Assertion failed: pdyna_poly_info->poly_num >= *pstart_poly_index + pbgdata->poly_num, file ../z_bgcheck.c, line 6687, thread 0

**Comment by DaMarkov** [comment]
The game softlocks because the following assertion is triggered:
`ASSERT(dyna->polyListMax >= *polyStartIndex + pbgdata->numPolygons, "pdyna_poly_info->poly_num >= *pstart_poly_index + pbgdata->poly_num", "../z_bgcheck.c", 6687);`
Game runs fine when removing the assertion. We could also change the line
`colCtx->dyna.polyListMax = 512;`
and increase it.

**Comment by DaMarkov** [comment]
Fixed in PR #166

**Comment by Zero3K** [comment]
The change was reverted. So, this ticket is being reopened.

**Comment by Zero3K** [comment]
Please try seeing if it still happens. It shouldn't since the mentioned PR has been committed in commit https://github.com/blawar/ooot/commit/fa5974477123a54933eaf3f9885f88b65a49b937.

**Comment by Zero3K** [comment]
I have been told in Discord that it has been fixed. So, I am closing this issue.
