### ISSUE TITLE
White space on map in Shadow Temple

### ISSUE THREAD

**Issue by Wesley107772** [blawar/ooot#127]
## Current Behavior

On the map in the Shadow Temple, on floor B2 there's a weird white rectangle on the left side.
Screenshot:
![ooot-map-issues-shadowtemple](https://user-images.githubusercontent.com/88684291/153681642-87339705-c851-4bef-84f1-a3627dc51084.jpg)

## Expected Behavior

The white rectangle should not be there.

## Steps to Reproduce

1. Go to map 75 (Shadow Temple)
2. Open the map.
3. Check floor B2.

**Comment by DaMarkov** [comment]
Fixed in 12163e9663f53a93610ebcc4d8719e42cedf3fd8
