### ISSUE TITLE
Link Decides to Morph Into the Floor When Z-Targeting and Slowly Moving Forward

### ISSUE THREAD

**Issue by MatttyMattHew** [blawar/ooot#13]
Edit: This may only happen in the Skulltula house, it seems to be the only area I've tried that has it.

![image](https://user-images.githubusercontent.com/98795913/151916665-26a1b418-a4a1-40f7-8faf-3ab30e6515e3.png)

**Comment by MMurphy4096** [comment]
Not just the Skulltulla house

https://user-images.githubusercontent.com/17395556/151917117-fc9898ca-9052-490b-9b64-95d754ffddea.mp4

**Comment by Chewbear67** [comment]
Z targeting and side stepping in Hyrule field gives me a similar result, not sure if that's location specific or not.

**Comment by DaMarkov** [comment]
Tested this as child link. It got fixed in the recent commits.

**Comment by Zero3K** [comment]
That's good.
