### ISSUE TITLE
Diving minigame zora does not appear after the first time

### ISSUE THREAD

**Issue by Wesley107772** [blawar/ooot#131]
## Current Behavior

The first time entering Zora's Domain as a child, the zora hosting the diving minigame is there as usual.
Upon leaving and re-entering, however, the zora does not reappear.
This persists until the game is restarted.

## Expected Behavior

The zora should always be there as child Link.

## Possible Solution

Possibly a similar issue to #115 and #122 

## Steps to Reproduce

1. Enter Zora's Domain as child Link. Verify that the zora is at the top of the waterfall.
2. Exit and re-enter Zora's Domain. Check for the zora again.

https://user-images.githubusercontent.com/88684291/153699918-a3c510eb-c236-4397-9ca7-f8379e71b284.mp4

**Comment by ajanhallinta** [comment]
Yet again boolean `static u8 D_809EF0B0` is set true in file `z_en_diving_game.c` in function `EnDivingGame_Init`, but is never set back to false. That variable being true in `EnDivingGame_Init` kills the actor.

**Comment by Wesley107772** [comment]
I experienced these issues on file 2 during a normal playthrough a few builds back

**Comment by blawar** [comment]
fixed
