### ISSUE TITLE
Lens of truth stretches with screen proportions

### ISSUE THREAD

**Issue by Wesley107772** [blawar/ooot#132]
This is not so much a bug report as it is a question.
Currently the lens of truth overlay stretches with the proportions of the screen, fully functional and everything.
Question is, is this intended behavior or should it be limited to 4:3?

![image](https://user-images.githubusercontent.com/88684291/153700521-3fa37261-b468-420f-b27f-92663603c919.png)
![image](https://user-images.githubusercontent.com/88684291/153700563-523a4e3c-e7c1-4513-b834-31cb7ce62f84.png)

**Comment by thomas992** [comment]
https://github.com/blawar/ooot/blob/master/src/code/z_vismono.c
I think this is the related code according to https://wiki.cloudmodding.com/oot/Source_Code_List

**Comment by DaMarkov** [comment]
I think having it as an oval is overall better.
When it's a circle we either have to make the circle so big that the lens effect is pointless or too small.
Now we could do something appropriate if we know the aspect ratio of the end-user.

But if we want something that that looks the same on 4:3 as the original and works for all aspect ratios I believe the oval is best,
