### ISSUE TITLE
Crash at Ganon Tower during the cinematic

### ISSUE THREAD

**Issue by waxmax1276** [blawar/ooot#133]
## Current Behavior

The game crash during the Ganon tower cinematic when the drum sound is requested

## Expected Behavior

The cinematic should continue and the fight start

## Possible Solution

An Exception is thrown at 0x0157BCEB in OOT.exe: 0xC0000005: Access violation reading location 0x44BC72D3.

In File : 
audio_load.c

Coming from the function : 
void AudioLoad_RelocateFont(s32 fontId, SoundFontData* mem, RelocInfo* relocInfo){

at this line : 
reloc = ((Drum**)ptrs[0])[i];

The issue is probably audio related

## Steps to Reproduce

1. Start debug menu
2. Choose Ganon Tower as either young or adult Link
3. Go through dialogues until crash
![OOT (Debugging) - Microsoft Visual Studio 2_12_2022 9_31_13 AM](https://user-images.githubusercontent.com/9160954/153715395-5f94ba5e-d91b-41a7-9bb5-7058d05fa5c8.png)

**Comment by Zero3K** [comment]
Does this issue happen anymore? It shouldn't since it is now playing audio almost properly.

**Comment by DaMarkov** [comment]
Fixed in Master Quest Debug.
It doesn't sounds pleasant, but the crash is gone.
