### ISSUE TITLE
The spinning object inside the Windmill doesn't appear after the first time.

### ISSUE THREAD

**Issue by ajanhallinta** [blawar/ooot#134]
## Current Behavior

The spinning object inside the Windmill doesn't appear when visiting second time there.

## Expected Behavior

The object should always appear.

## Possible Solution

Most likely a similar issue to #131 #122 #115 

## Steps to Reproduce

1. Enter the Windmill, exit and enter again.

![windmill2](https://user-images.githubusercontent.com/26453696/153721136-e591f043-881a-4132-aed2-00aedc8ed306.png)

**Comment by blawar** [comment]
fixed
