### ISSUE TITLE
Treasure Chest Game Man doesn't appear after the first time

### ISSUE THREAD

**Issue by ajanhallinta** [blawar/ooot#135]
## Current Behavior

Treasure Chest Game Man doesn't spawn when visiting second time in Treasure Chest Game.

## Expected Behavior

He should be always spawn.

## Possible Solution

In file `z_en_takara_man.c` variable `sTakaraIsInitialized` is set to true, but is never set back to false, which prevents the actor from spawning next time. Similar to issue #134 #131 #122 #115

## Steps to Reproduce

1. Visit Treasure Chest Game, exit and re-enter.

![treasure1](https://user-images.githubusercontent.com/26453696/153723193-3a6412a0-27ef-45e0-8d86-d91b79398152.png)

**Comment by blawar** [comment]
fixed
