### ISSUE TITLE
Navi through walls

### ISSUE THREAD

**Issue by thomas992** [blawar/ooot#136]
screenshot https://imgur.com/RCD8m0b
## Current Behavior
Navi appears through objects, as does in retail N64.

## Expected Behavior
The fairy should be hidden behind objects and the game updated to avoid bad camera angles for fairy messages

## Possible Solution
if this was CSS you would adjust the z-index

## Steps to Reproduce
1. talk to Navi near an obstruction

## Context (Environment)
I am actually running this on WINE and the sound does not work

## Detailed Description
Fairies should be hidden behind walls

## Possible Implementation
maybe partial transparency behind walls?

**Comment by mrneo240** [comment]
I believe this is consistent on n64. Can you verify?

**Comment by thomas992** [comment]
I do not think it is intended game behavior, light does not travel through barriers, be it from a fairy or an artificial light source.

**Comment by Zelllll** [comment]
Yeah this is intended, n64 does this too

**Comment by thomas992** [comment]
I think in the sceenshot I present, a tracer checking for collision could instruct the game to use an alternate camera angle to see Navi from behind Link or whatever

**Comment by Zelllll** [comment]
I think Navi just doesn't use Z buffering, which is probably intentional, to make sure that you always know where Navi is.

**Comment by thomas992** [comment]
If you run a line from where the camera was suppose to be to where NaVi is speaking from and there is a physical barrier, opting to use an alternate angle that is not obstructed would prevent this type of scene.

**Comment by mrneo240** [comment]
Please provide n64 hardware reference showing what you're describing.

**Comment by thomas992** [comment]
I do not have the means of replicating this on original hardware now but I believe that this is indeed "intended" behavior meaning the same as the N64. It looks like a glitch, I think if it has to appear through walls we can mitigate how apparent it is by changing camera angles if necessary and updating how it does render through walls.

**Comment by xoascf** [comment]
I'm pretty sure this is intended, even the 3DS version does it this way:
![capture](https://user-images.githubusercontent.com/28744392/156635333-3dbbc91d-9850-4901-bae8-8a4091658e3c.png)

**Comment by thomas992** [comment]
> I'm pretty sure this is intended, even the 3DS version does it this way: ![capture](https://user-images.githubusercontent.com/28744392/156635333-3dbbc91d-9850-4901-bae8-8a4091658e3c.png)

![capture](https://live.staticflickr.com/65535/52085721688_5719b4e200_b.jpg)
not on xbox
