### ISSUE TITLE
GLideN64 window has issues on boot

### ISSUE THREAD

**Issue by Zelllll** [blawar/ooot#137]
If you open the .exe, GlideN64 will give "Error setting pixel format," however this luckily does not seem to cause any other issues.
![image](https://user-images.githubusercontent.com/56516451/153726896-5d346d3b-8399-46a7-916c-4a8e5f2e1dbb.png)
## Current Behavior

The error happens, but should not.
## Expected Behavior

The error happens, but should not.
## Possible Solution

This seems to be an issue with the window resolution, so that may help find the solution.
## Steps to Reproduce

1. Open OOT.exe

**Comment by DaMarkov** [comment]
This happens due to `SetPixelFormat()` returning false in gliden64 in `WindowsWGL.cpp`.
Can you use the debugger to check what value `pixelFormat` has?
You might have to disable optimizations for gliden64 first.

**Comment by GreenSwede** [comment]
To contribute further with input, my main PC never encounters this error when starting the game. However, my Surface Pro laptop does encounter this error. What could be different between the two?

**Comment by Zero3K** [comment]
![image](https://user-images.githubusercontent.com/6194332/154782970-23ea6e53-c755-4288-ad91-85e5b11b67d7.png)

**Comment by Zero3K** [comment]
I think this issue can be solved by having it not change the color depth if it is at 16 or 32 bit.

**Comment by DaMarkov** [comment]
Fixed in a PR for gliden64

**Comment by Zero3K** [comment]
Fixed thanks to @DaMarkov notifying me about the line of code responsible. I made a PR (#174) which removes the line and then merged it.
