### ISSUE TITLE
Widescreen Causing Scene Out Of Bounds

### ISSUE THREAD

**Issue by thomas992** [blawar/ooot#138]
screenshot: https://imgur.com/a/Pn1FMgn
after defeating gohma in the cutscene that follows you can see out of bounds rendering (look at the bottom right), it is more apparent in transition. I suspect there to be more scenes with this behavior

## Current Behavior
the wide screen aspect causes a visual glitch

## Expected Behavior
the camera placement, and map allow for a good rendering with the entire screen not clipping through walls

## Possible Solution
adjusting camera positions in scenes and or updating maps

## Steps to Reproduce
1. defeat gohma, warp out
2. when the great deku tree is speaking you will see the visual glitch bottom right

## Context (Environment)
Running WINE

**Comment by mrneo240** [comment]
@thomas992 can you highlight the glitch? I don't see it

**Comment by Wesley107772** [comment]
![image](https://user-images.githubusercontent.com/88684291/153730585-90b6e8b3-de8f-4e40-b5f9-9f7457b7a412.png)
I believe it's this, it cuts off the ground in front and the green texture you see is from all the way in the back

**Comment by mrneo240** [comment]
level geometry changes seem like enhancement.
closed.
