### ISSUE TITLE
Bar atop screen when crashing into object with roll in Back Alley in Hyrule Castle Town

### ISSUE THREAD

**Issue by davetroutt** [blawar/ooot#141]
Green, yellow and black bar appears at op of screen when crashing into object with roll in Back Alley in Hyrule Castle Town

## Current Behavior

Bar appears

## Expected Behavior

Bar should not appear

## Possible Solution

N/A

## Steps to Reproduce

https://www.youtube.com/watch?v=sFD58zxiqfA

## Context (Environment)

Just a visual glitch

**Comment by DaMarkov** [comment]
This looks very much like a frame buffer emulation glitch in GLideN64.
This also happens in Project64.

**Comment by Jj0YzL5nvJ** [comment]
This is most likely a bug in the game, the background texture is not high enough and the rolling effect exposes the geometry behind. The same behaviour can be reproduced with Mupen64Plus + CXD4 + Angrylion-Plus.

See: gonetz/GLideN64#2051

**Comment by DaMarkov** [comment]
This actually got worse somehow (no idea due to which commit)
![image](https://user-images.githubusercontent.com/35939509/160258367-a9f501b0-7373-4603-9427-1acf03de00a8.png)

So this is no longer a minor graphical glitch.

**Comment by DaMarkov** [comment]
Suggest solution is to disable the quake/screen shake effect for all scenes with a pre-rendered background.
See PR #224

**Comment by mario8000** [comment]
Confirmed working in the dev branch created to test this fix

**Comment by xoascf** [comment]
> This actually got worse somehow (no idea due to which commit) ![image](https://user-images.githubusercontent.com/35939509/160258367-a9f501b0-7373-4603-9427-1acf03de00a8.png)
> 
> So this is no longer a minor graphical glitch.

@DaMarkov, that glitch(? was introduced as a side effect of commit 22967f9.
