### ISSUE TITLE
Game crashes when entering Hyrule Garden during daytime

### ISSUE THREAD

**Issue by Lehpumeh** [blawar/ooot#142]
## Current Behavior

Entering the Hyrule Garden to progress the game crashes the game. Entering at night doesn't crash the game, but you can't progress during night.
## Expected Behavior

Going through shouldn't crash the game.
## Steps to Reproduce

1. Wake Talon and talk to him so he isn't blocking the pushable blocks.
2. Push blocks into place and jump to the ledge you need to crawl through
3. Crawl into it

Note: Map select on a fresh save also reproduces it. (Hyrule Garden Minigame)
## Context (Environment)
Im trying to progress the game by going through the garden and get to Zelda for her letter and to get Zelda's Lullaby song.

https://user-images.githubusercontent.com/99471756/153743012-a6624515-b766-4871-a68a-94f59244a2c4.mp4

**Comment by GreenSwede** [comment]
This can be closed. Fix pushed for retail.

https://github.com/blawar/ooot/commit/78c346f544bd235aa28c108247cb359f432eb712

**Comment by Zero3K** [comment]
This (and possibly other issues) is happening again after the latest changes.

**Comment by Zero3K** [comment]
I think it was fixed again thanks to commit https://github.com/blawar/ooot/commit/9a6359521c2edc7781bbaf1476acb17f5f45e6e8.
