### ISSUE TITLE
Boss name graphical glitch

### ISSUE THREAD

**Issue by Daniel6372** [blawar/ooot#146]
## Current Behavior

A vertical line is visible in the names of the bosses that are displayed upon initializing each boss fight.
## Expected Behavior

The vertical line should not appear, as it does not on original hardware.
## Possible Solution

To my knowledge it's a filtering issue, something that needs to be adjusted in GlideN64 options.
## Steps to Reproduce

1. Create File 1
2. Use the initial debug menu and select any of the following locations (boss rooms): "67: Gohmas Lair", "69: King Dodongos Lair", "71: Barinades Lair", "73: Phantom Ganons Lair", "76: Bongo Bongos Lair", "78: Volvagias Lair", "80: Morphas Lair", "82: Iron Knuckles Lair", "83: Twinrovas Lair", "85: Ganondorfs Lair". Not sure if it happens on all of them, but it does on most. One exception is the "89: Final Fight With Ganon" which does not exhibit this behavior on emulator, but it crashes in the port anyway ( #133 / #108 ) so can't test it.
3. Initiate the boss fight and the text will show at the end of the boss introduction scene.
## Detailed Description

![Screenshot (69)-2](https://user-images.githubusercontent.com/47946277/153768323-6b070081-3b93-4196-b89e-3b7f232a1f82.png)
![Screenshot (68)-2](https://user-images.githubusercontent.com/47946277/153768329-9397ede0-60e7-4940-ae92-3889d2b16cae.png)
This issue seems to be the same that often happens with emulators, here's an example video of emulator footage, linked directly to the timestamp.
https://youtu.be/3QMOyf5f4xU?t=37
Might be related to a similar issue that happens in Mario Kart 64 on emulators:
https://user-images.githubusercontent.com/37382324/37494299-75686784-2865-11e8-8dcb-9f0f92fcce59.png

**Comment by DaMarkov** [comment]
The boss title textures are all tiled textures.
Looks like we are off by 1 pixel. Could this also be the reason we get the wrong hash in GLideN64 for tiled textures?

**Comment by DaMarkov** [comment]
Nope, it's the game that is off by half a pixel. This requires a PR in gliden, but it's quite easy.

![image](https://user-images.githubusercontent.com/35939509/154819712-0f65212b-315e-4248-8352-a419b0eefef5.png)

**Comment by DaMarkov** [comment]
Fixed in ad7777246f05f200585819497a15057caaa3b461
