### ISSUE TITLE
Game crashes when going up Death Mountain Trail on the way to Goron City as Child

### ISSUE THREAD

**Issue by Lehpumeh** [blawar/ooot#148]
## Current Behavior

Going up Death Mountain Trail to get to Goron City crashes at the point you see the rolling goron.
## Expected Behavior

It shouldn't crash.
## Steps to Reproduce

1. Enter the Trail and follow the path to Goron City.

## Context (Environment)

Can't get to goron city for the goron bracelet in order to continue the game.

https://user-images.githubusercontent.com/99471756/153787692-116aab2f-93ab-4fa0-a86c-6f95589651d6.mp4

**Comment by DaMarkov** [comment]
Is there a good way to reproduce this?
I played around this area, but it didn't crash for me.

**Comment by Lehpumeh** [comment]
It crashes for me on Retail, but doesn't crash on MQ Debug

**Comment by DaMarkov** [comment]
Thanks! That explains why I couldn't reproduce it.

**Comment by ajanhallinta** [comment]
Some actors seems to have null `path->points`, when using functions from `z_path.c`. At least releasing Gorons in Fire Temple, and changing scene with Richard in the Market seems to cause a similar crash.

**Comment by Zero3K** [comment]
@Lehpumeh wrote in Discord that it has been fixed on PAL.
