### ISSUE TITLE
Boulder in the Goron Ruby cutscene

### ISSUE THREAD

**Issue by Lehpumeh** [blawar/ooot#149]
## Current Behavior

When you beat Dodongo's Cavern and enter the cutscene for the Goron Ruby, the boulder you blew up to get into the cavern shows up in the cutscene.
## Expected Behavior

Boulder should be gone
## Steps to Reproduce

1. Beat King Dodongo and enter the blue portal to start the cutscene.

Note: Death Mountain Trail on the map select through "Stage : Demo01" plays the cutscene.
## Context (Environment)

It's not game breaking. The boulder doesn't actually come back after the cutscene is over. Just shows in the scene.

https://user-images.githubusercontent.com/99471756/153793069-4bfc9593-0593-4827-852d-c7384547e516.mp4

**Comment by Zero3K** [comment]
Duplicate of #128.
