### ISSUE TITLE
Cursor Missing in Pause Screen

### ISSUE THREAD

**Issue by MatttyMattHew** [blawar/ooot#16]
![image](https://user-images.githubusercontent.com/98795913/151926429-fb881033-fc74-4072-b354-a1ca4d839787.png)

**Comment by DaMarkov** [comment]
I tried to fix this, but so far I failed.
I believe the relevant code is: https://github.com/blawar/ooot/blob/master/src/overlays/misc/ovl_kaleido_scope/z_kaleido_scope_PAL.c#L477

`gDPSetPrimColor` sets the color to yellow. The `D_808*` variables are used for the glow animation.
I don't know if there is something wrong with the texture.

This is how it's supposed to look:
![image](https://user-images.githubusercontent.com/35939509/153216391-d74f1b50-744d-4201-99fc-ff3e93d0c3a6.png)

**Comment by blawar** [comment]
This bug looks similar to the beating heart bug @DaMarkov, might be related.

**Comment by DaMarkov** [comment]
@blawar you were right. Thanks a lot!!
I changed the vertex data and got this. I think I can fix this issue.
![image](https://user-images.githubusercontent.com/35939509/153291691-1e6cd1be-789f-4725-8284-f04e59f357b1.png)

**Comment by DaMarkov** [comment]
Fixed in PR #100

**Comment by Zero3K** [comment]
This has been fixed since PR #100 has been merged.
