### ISSUE TITLE
King Zora is broken

### ISSUE THREAD

**Issue by Lehpumeh** [blawar/ooot#167]
## Current Behavior

King Zora flys away in a never ending cutscene
## Expected Behavior

He should Mweep over to his right so he isn't blocking the path.
## Steps to Reproduce

1. Give yourself Silver Scale to get the Letter in a bottle at Lake Hylia or just give yourself the Letter in the bottle.
2. Show it to King Zora and he will mweep somewhere else and wont stop.
## Context (Environment)

Its game breaking because you need to pass him to get to Lord Jabu Jabu

https://user-images.githubusercontent.com/99471756/154815491-a10602dc-8c8a-4210-8751-0eeff88b18b5.mp4

**Comment by DaMarkov** [comment]
Can not reproduce on master when supplying the master quest debug rom.

**Comment by Zero3K** [comment]
Maybe it is a Retail ROM issue?

**Comment by DaMarkov** [comment]
So I assume this is some issue with ZAPD extraction.

**Comment by blawar** [comment]
should be fixed, pull master, re-run setup.py.  re-open if the issue persists.
