### ISSUE TITLE
Hookshot and Longshot way too long.

### ISSUE THREAD

**Issue by Lehpumeh** [blawar/ooot#169]
## Current Behavior

Both Hookshot and Longshot are a lot longer than it should be.

Happens in Retail and Master Quest
## Expected Behavior

The length of how far the chain goes should be way less
## Steps to Reproduce

1. Equip Hookshot or Longshot and shoot something further away than you normally could
## Context (Environment)

Video shows me comparing just the longshot from PC port to emulator, but Hookshot is also too long and it also happens on Retail.

https://user-images.githubusercontent.com/99471756/154821194-621cff63-e984-42ed-bf9e-6a533a7b7238.mp4

**Comment by blawar** [comment]
fixed
