### ISSUE TITLE
Screen Effects Not Scaled to 21:9

### ISSUE THREAD

**Issue by MatttyMattHew** [blawar/ooot#17]
![image](https://user-images.githubusercontent.com/98795913/151926869-75017f6d-c847-46d4-bce2-514a602f6a2f.png)

**Comment by blawar** [comment]
I’m not sure how to change this, or if it should be changed.  We could transform the circle into an oval to fill the screen, but I’m not sure if that would be ideal.  Leaving open til a solution is determined.

**Comment by DaMarkov** [comment]
Transformed in a slight oval in PR #165.
![image](https://user-images.githubusercontent.com/35939509/154773644-83f17d06-f386-4f96-a86b-130cda1a830b.png)
