### ISSUE TITLE
Wrong doors in Forest Temple in Retail and Master Quest

### ISSUE THREAD

**Issue by Lehpumeh** [blawar/ooot#170]
## Current Behavior

Doors are using normal wooden doors
## Expected Behavior

Forest temple has their own doors
## Steps to Reproduce

1. Go to forest temple and observe doors

__HOW THEY SHOULD BE__
![image](https://user-images.githubusercontent.com/99471756/154821726-03a72884-3315-4815-b309-c0fb4770dfe7.png)
__WHAT THEY LOOK LIKE IN PC PORT__
![image](https://user-images.githubusercontent.com/99471756/154821740-3ef39070-a172-417f-ab55-e815c4e8850a.png)

**Comment by DaMarkov** [comment]
Fixed in PR #173.

**Comment by Zero3K** [comment]
Can you please show proof that it has been fixed?
