### ISSUE TITLE
Big Skulltulas are slower than normal both Retail and Master Quest

### ISSUE THREAD

**Issue by Lehpumeh** [blawar/ooot#171]
## Current Behavior

Big Skulltulas animations are slow
## Expected Behavior

Should be faster

## Context (Environment)

Similar to #162

https://user-images.githubusercontent.com/99471756/154822320-55a1c3d7-79a5-4e52-836a-a7ffa51dfe37.mp4

**Comment by DaMarkov** [comment]
I also noticed this today when I had to play through the forest temple a bunch of times.
Happens in master quest debug. I think the Skulltulas behaved correctly a week ago or so.

**Comment by DaMarkov** [comment]
This is due to the recent change to support higher framerates.

In `EnSt_Update` the function `func_8002D7EC` is called.
I assume `const f32 speedRate = FRAMERATE_ANIM_SCALER;` is wrong in the case of the Skulltula.

**Comment by blawar** [comment]
fixed
