### ISSUE TITLE
Rumble doesnt stop after the volcano erupts when you beat Volvagia

### ISSUE THREAD

**Issue by Lehpumeh** [blawar/ooot#172]
## Current Behavior

When you beat Volvagia and start the cutscene of the Volcano erupting the rumble wont stop till you trigger the rumble another way like rolling into a wall.

## Steps to Reproduce

 Map select "2 : Kakarkio Village | Stage: Demo03" is the cutscene

**Comment by DaMarkov** [comment]
Fixed in commit 501f9f2f75e0086c4799ea93ae72577766262ecc
