### ISSUE TITLE
Using bow on Epona doesn't go to first person on Retail and Master Quest

### ISSUE THREAD

**Issue by Lehpumeh** [blawar/ooot#179]
## Current Behavior

Camera doesn't go into first person when pulling out the bow
## Expected Behavior

Should go into first person
## Steps to Reproduce

Pull bow out on Epona

https://user-images.githubusercontent.com/99471756/154872028-90fa6629-d9b0-4738-a5eb-d4a4f3cbd33e.mp4

**Comment by blawar** [comment]
should be fixed.
