### ISSUE TITLE
Objects are unloaded on screen at 21:9

### ISSUE THREAD

**Issue by MatttyMattHew** [blawar/ooot#18]
The trees on the left

![image](https://user-images.githubusercontent.com/98795913/151927038-e5f725b7-b90c-45b5-9760-f4cf9804f02b.png)

![image](https://user-images.githubusercontent.com/98795913/151927074-41250018-4b18-4128-b7f2-e79454bb5a3d.png)

**Comment by blawar** [comment]
fixed
