### ISSUE TITLE
Crash when charge spin attacking stalchildren

### ISSUE THREAD

**Issue by Lehpumeh** [blawar/ooot#183]
## Current Behavior

Charging a spin attack and hitting 2 Stalchildren will crash the game in Hyrule Field near Kokiri Forest entrance
## Steps to Reproduce

1. Go to Hyrule Field at night near the Peahat in front of the Kokiri Forest Entrance.
2. Charge Spin Attack (Red beam) 2 Stalchildren at the same time until it crashes.

## Context (Environment)

The only place it crashes is near Kokiri Forest Entrance. I couldn't get it to crash anywhere else on Hyrule Field albeit I was only trying in a few places (In front of the castle, near a peahat near Gerudo Valley Entrance and near Lake Hylia Entrance)

Happens in Retail and Master Quest

https://user-images.githubusercontent.com/99471756/155246025-09c72dac-9b2c-40ca-a612-52435b2e70d8.mp4

__The get two different exceptions thrown, but i mostly get the Line 353 error__

![image](https://user-images.githubusercontent.com/99471756/155246058-231117c7-7eaf-4e5c-8efb-4d77bdafabaf.png)

![image](https://user-images.githubusercontent.com/99471756/155246299-203c09f6-833b-48f6-8aba-74796752aeed.png)

**Comment by Zero3K** [comment]
Please try seeing if it still happens. It shouldn't since it seems to be related to the issue that commit https://github.com/blawar/ooot/commit/fa5974477123a54933eaf3f9885f88b65a49b937 fixed.

**Comment by Zero3K** [comment]
I got it happening in a different location now:

![image](https://user-images.githubusercontent.com/6194332/156483289-90c61fb2-8351-4f98-bd94-c327599a3660.png)

**Comment by Zero3K** [comment]
Its a null pointer according to @blawar.

**Comment by DaMarkov** [comment]
This might be fixed via PR #206

**Comment by DaMarkov** [comment]
Does this issue still exist?

**Comment by Lehpumeh** [comment]
Your fix for the Jabu Jabu freeze fixed this as well. I couldn't make it crash since then.
