### ISSUE TITLE
Color of A button is Green instead of Blue OOT PAL 1.0

### ISSUE THREAD

**Issue by nitrostemp** [blawar/ooot#185]
## Expected Behavior
Color of A button when composing song should be blue.
## Possible Solution
Possible incorrect button texture loaded.

## Steps to Reproduce

1.Play song
2.Look at notes
3.Wrong color while composing
4.Updates to correct song when composed

![Songs](https://user-images.githubusercontent.com/39111880/155836000-654104c4-3254-4341-9a2b-c9d563b16d06.png)

**Comment by Daniel6372** [comment]
I believe this is due to the Master Quest Debug rom containing assets for the gamecube controller which had a green A button and a red B button.

**Comment by queenkjuul** [comment]
Just found this project today - it looks like these colors are defined in z_message_PAL.cpp/Message_DrawMain(), however I've tried editing the A button RGB values there and rebuilding but it doesn't seem to affect anything. 

The default value of (100, 255, 200) seems to line up exactly with the shade of green in the screenshot, so I'm not sure why changing it to (50,50,255) didn't result in anything when I rebuilt it - but again, just started looking. 

maybe this points someone else in the right direction

**Comment by queenkjuul** [comment]
nevermind I figured it out with help from @bcary PR is open

**Comment by blawar** [comment]
Please resubmit your PR @queenkjuul
