### ISSUE TITLE
Attempting to catch a poe crashes the game

### ISSUE THREAD

**Issue by MatttyMattHew** [blawar/ooot#19]
[process exited with code 3489660927]

![image](https://user-images.githubusercontent.com/98795913/151927698-4ab7be54-c892-40b1-b42a-afad9cf57e08.png)

**Comment by Zero3K** [comment]
It might be related to #41.

**Comment by DaMarkov** [comment]
Due to
`this->objectIdx = Object_GetIndex(&globalCtx->objectCtx, OBJECT_POH);`
`objectIdx` should be `s32`, so this issue might be fixed when PR #69 is merged.

**Comment by Zero3K** [comment]
They are separate files. So, the fix will have to be applied to the file for the Poe and others.

**Comment by mrneo240** [comment]
fix has been created, its related to sound not being present
mrneo240/ooot-lite@691d294fb59de22dc3833b234e057020e5f9b9bd

**Comment by blawar** [comment]
fixed in audio branch.
