### ISSUE TITLE
VS2022 Win10 build is not working

### ISSUE THREAD

**Issue by xcom169** [blawar/ooot#193]
VS2022 Win10 build is not working

## Current Behavior
Win 10 build is not working
![image](https://user-images.githubusercontent.com/17802090/156343480-ca552722-5fe8-44e3-9ae1-3a9280d0ca8a.png)

## Expected Behavior
Build should be done. 

## Possible Solution
Re-target the project to Win10 SDK?

## Steps to Reproduce

1. Open up the solution file
2. Click on Build Win32
3. Check errors list
4.

## Context (Environment)
I try to build the solution on Win10 with VS2022

## Detailed Description
Please help how to retarget the solution to Win10SDK.

**Comment by nitrostemp** [comment]
this is being worked on as per pull request: https://github.com/blawar/ooot/pull/189

**Comment by nitrostemp** [comment]
also solution is to remove _xp from the toolset field in aziaudio: 
![image](https://user-images.githubusercontent.com/39111880/156357412-1af02438-a18c-4d7a-9f2a-cd5844dbb73f.png)

**Comment by xcom169** [comment]
Thanks a lot! I'll try.

**Comment by xoascf** [comment]
> this is being worked on as per pull request: #189

*https://github.com/blawar/AziAudio/pull/3

**Comment by Zero3K** [comment]
It should be fixed now. Please try updating it via TortiseGit's Update Submodule context menu item and then building OOT.exe.

**Comment by GreenSwede** [comment]
If you don't use TortoiseGit, you can run `git submodule update --init`

**Comment by xcom169** [comment]
Thanks a lot
