### ISSUE TITLE
Link looks away when equipping an item

### ISSUE THREAD

**Issue by Wesley107772** [blawar/ooot#195]
## Current Behavior

When equipping a piece of equipment, Link suddenly looks away from the camera.
## Expected Behavior

Link shouldn't avert his gaze and should simply continue to stare us into the eyes.
## Steps to Reproduce

1. Start a debug game as child or adult Link.
2. Equip any piece of equipment.
## Detailed Description

The video only shows child Link, but this applies to adult Link as well.

https://user-images.githubusercontent.com/88684291/156638541-683c0ee7-8538-42e3-aaef-5eafed5c94d9.mp4

**Comment by blawar** [comment]
how did you even notice this?  superhuman hah.
