### ISSUE TITLE
Make Iron Boots an item

### ISSUE THREAD

**Issue by wabberz** [blawar/ooot#198]
## Current Behavior
Boots need to be switched in the Equipment screen in the menu

## Expected Behavior
Boots can be used as a C-Button item like in the 3DS version

**Comment by DaMarkov** [comment]
Wouldn't it be better to having something like a quick select ring menu?
I would argue that Iron Boots as an item would take away an item slot.
In the water temple you always want the Iron Boots and the Ocarina on one of the C buttons.
That would leave only one C button free for Bow/Bombs etc.

The other idea would be to have a button to swap boots. Would also be useful for the hover boots in the Shadow Temple.

**Comment by mario8000** [comment]
Assigning boots to a C button works great, however once your underwater you cant change boots with C and must open up the pause menu to change back to regular boots. Make C buttons with equipment assigned usable underwater

**Comment by mario8000** [comment]
![image](https://user-images.githubusercontent.com/24818108/157562993-143f66ea-7694-4502-9a5e-9ecc015e8b3f.png)

**Comment by nitrostemp** [comment]
what we really need is it to toggle between boots like in the randomizer.

**Comment by blawar** [comment]
> what we really need is it to toggle between boots like in the randomizer.

Press F1 on master.
