### ISSUE TITLE
Add 3-Point Filtering

### ISSUE THREAD

**Issue by VioBeeyo** [blawar/ooot#2]
The Port as of now lacks this. Making some textures such as the Stairs in Kakariko Village look wonky.

![uOKmsXT](https://user-images.githubusercontent.com/95020200/151914950-dc00f325-6b48-4a41-bef3-206ad6cb118b.jpeg)

**Comment by blawar** [comment]
edit GLideN64.ini

texture\bilinearMode=0

these are the values:

#define BILINEAR_3POINT   0
#define BILINEAR_STANDARD 1
#define BILINEAR_3POINT_WITH_COLOR_BLEEDING 2
#define BILINEAR_STANDARD_WITH_COLOR_BLEEDING_AND_PREMULTIPLIED_ALPHA 3

**Comment by VioBeeyo** [comment]
Went to the .ini and set texture\bilinearMode to 1

Then went and set #define BILINEAR_3POINT to 1

This is the result:
![HIcfPI8](https://user-images.githubusercontent.com/95020200/151986543-7a790e92-53c1-4e0f-9959-ef03391f21b5.jpeg)

**Comment by VioBeeyo** [comment]
This is what the 3-point filtering looks like on actual N64 Hardware. So I am guessing that the GlideN64 Impl
![IMG_0935](https://user-images.githubusercontent.com/95020200/152008824-1a568581-bb38-4a75-b172-baa326b0dea8.jpg)
ementation is accuarate enough.

This issue can be closed.
