### ISSUE TITLE
Game Crashes During Credits

### ISSUE THREAD

**Issue by MatttyMattHew** [blawar/ooot#20]
[process exited with code 3221225477]

**Comment by mzxrules** [comment]
likely related to this line: 
https://github.com/blawar/ooot/blob/master/src/code/z_play.c#L373

**Comment by DaMarkov** [comment]
This should be fixed as soon as PR #49 is merged.

**Comment by Zero3K** [comment]
Please retest since #49 was merged.

**Comment by blawar** [comment]
Unable to reproduce with master, presumed fixed.  Please re-open if the issue persists.
