### ISSUE TITLE
Bombchu level gets corrupted if you play long enough

### ISSUE THREAD

**Issue by mario8000** [blawar/ooot#207]
## Current Behavior

if you play through the bombchu game long enough, the level becomes corrupted. PAL 1.0 Retail version
https://youtu.be/MZyXK3iO5ko
## Expected Behavior

play though normally, no adverse graphics
## Steps to Reproduce

1. play bombchu game
2. keep playing until you find the corrupted level, took about 4 games

**Comment by Wesley107772** [comment]
Can confirm that this is also present in MQD. For me I remember it staying normal when winning the first time, but after losing and trying again it got like this. Haven't tested it further yet
![Screenshot_13](https://user-images.githubusercontent.com/88684291/157052831-dd5c87b2-0b39-4986-b36b-68bd2c8da334.png)
