### ISSUE TITLE
Rolling into the wall in certain areas causes a graphical error

### ISSUE THREAD

**Issue by mario8000** [blawar/ooot#209]
Rolling into a wall in the first area when you enter the Market causes the graphics to turn green on the screen. I'm assuming this is due to the screen shake effect? I also got this to happen right outside the temple of time
## Current Behavior

https://youtu.be/y10xlsCkcy4 objects on the screen turn green when you roll into a wall in the opening area in the market. Tried rolling into a couple different walls in different areas nearby as well. Seems to apply to other areas as well not just here.

## Expected Behavior

Screen shakes a little when you roll into a wall, no graphical errors

## Steps to Reproduce

1. go to market as either adult or young link
2. roll into a wall in the market drawbridge area

**Comment by DaMarkov** [comment]
This is the same issue as in #141, correct?

**Comment by mario8000** [comment]
> This is the same issue as in #141, correct?

yes it can be merged with that if needed. Happens in multiple areas but only outside of temple of time, draw bridge area and that ally he mentions
