### ISSUE TITLE
Lighting broken in temple of time

### ISSUE THREAD

**Issue by MatttyMattHew** [blawar/ooot#22]
![image](https://user-images.githubusercontent.com/98795913/151930622-0f696312-3353-4276-a97d-d6ce565e05cd.png)
![image](https://user-images.githubusercontent.com/98795913/151930680-66ce64ab-46f3-4aef-a960-87bb22c152a0.png)

**Comment by Zero3K** [comment]
This might be fixed by commit https://github.com/blawar/ooot/commit/ac2b25f6a5030a23867a68e989b104c2af11d340.

**Comment by Zero3K** [comment]
I do not notice it anymore in the latest master.
