### ISSUE TITLE
Missing oot.props imported by OOT.vcxproj

### ISSUE THREAD

**Issue by lRn2Win** [blawar/ooot#226]
## Current Behavior
Trying to open the OOT sln causes an import error with missing "oot.props" file. 

"ooot\vs\OOT_Assets.vcxproj : error  : The imported project \ooot\vs\oot.props" was not found. Confirm that the path in the <Import> declaration is correct, and that the file exists on disk.  \ooot\vs\OOT_Assets.vcxproj"

## Expected Behavior
The project file OOT.vcxproj and OOT_Assets.vcxproj should succeed.

## Possible Solution
Add oot.props file.

## Steps to Reproduce

1. Open the solution file OOT.sln with VS 2019

## Context (Environment)

Can't build the solution.

**Comment by Zero3K** [comment]
You have to run setup.py for oot.props to be made.
