### ISSUE TITLE
Pressing SELECT on the opening screen lets you control Link and Epona

### ISSUE THREAD

**Issue by mario8000** [blawar/ooot#228]
## Current Behavior

Pressing SELECT on the opening screen lets you control Link and Epona. This is very strange and you can actually roam around Hyrule Field with the "PRESS START" screen up with the logo. The map and HUD is present as well when you do this. Using the MQ Debug ROM. This is also with the level select DISABLED.
![image](https://user-images.githubusercontent.com/24818108/160302264-56b5246c-e1eb-43ca-b1da-8de9fdcb0ee2.png)

## Expected Behavior

nothing should happen when you press SELECT

## Steps to Reproduce

1.Launch game
2.wait for Link and Epona to appear on screen
3.Press select

**Comment by DaMarkov** [comment]
I think this is one of the demo scenes.
By select, do you mean pressing the start button?

At what time precisely do I need to press the button to reproduce this?

**Comment by mario8000** [comment]
Select (on Xbox controller), or level select button with the level select disabled

**Comment by Lehpumeh** [comment]
I think this is because the Debug tools themselves aren't fully disabled, just the map select. For some reason the Select button is bound to Left Right Up and Down on Dpad and pressing Right on dpad will give you control of link in cutscenes.

**Comment by DaMarkov** [comment]
Yes, I have found the bug. It's just a question of how to fix it. The bug is
````
if (CHECK_BTN_ALL(globalCtx->state.input[0].press.button, BTN_DRIGHT)) {
        csCtx->state = CS_STATE_UNSKIPPABLE_INIT;
        return;
    }
````
in `z_demo.cpp`
