### ISSUE TITLE
Cutscene lighting broken 

### ISSUE THREAD

**Issue by MatttyMattHew** [blawar/ooot#23]
![image](https://user-images.githubusercontent.com/98795913/151931415-18d65b16-d0da-4d6b-ae30-2e850cc8cdc0.png)

**Comment by Zero3K** [comment]
This should be fixed by commit https://github.com/blawar/ooot/commit/ac2b25f6a5030a23867a68e989b104c2af11d340.

**Comment by blawar** [comment]
Presumed fixed by FBE, reopen if the issue persists.
