### ISSUE TITLE
Missing graphics from the Deku Tree story cutscenes after beating Gohma

### ISSUE THREAD

**Issue by Lehpumeh** [blawar/ooot#231]
## Current Behavior

A blue aura that should be around Link when warping from the Gohma boss room to the outside is missing
![image](https://user-images.githubusercontent.com/99471756/160314153-1b37888c-61fd-4fbd-823e-49bce9eae999.png)

When his story starts with Ganondorf on his horse the fire surrounding him and the lightning graphics don't show.

![image](https://user-images.githubusercontent.com/99471756/160314323-adb78cde-7999-411e-b8c5-17d4769c2e38.png)

## Steps to Reproduce

1. Level select [4: Zoras River - Demo01]

**Comment by DaMarkov** [comment]
Actually, the fire effect got fixed when I fixed the lens flare effect in PR #239.
So, this issue can be closed when these two PRs have moved into the master branch.

**Comment by Lehpumeh** [comment]
Fixed in PR https://github.com/blawar/ooot/pull/239 and https://github.com/blawar/ooot/pull/241
