### ISSUE TITLE
Sunbeams are missing from the sun

### ISSUE THREAD

**Issue by Lehpumeh** [blawar/ooot#234]
## Current Behavior

Sunbeams are missing from the sun, noticeable in cutscenes and just looking at it.

![image](https://user-images.githubusercontent.com/99471756/160317806-e7d24e8c-685e-4b4b-b21f-695126b92a69.png)

## Steps to Reproduce

1. Load the game and look up at the sun

**Comment by blawar** [comment]
should be fixed, re-open if the issue persists.
