### ISSUE TITLE
Saria invisible in opening cutscene

### ISSUE THREAD

**Issue by Dewey-Wilkerson** [blawar/ooot#24]
Just plain emptiness

![image](https://user-images.githubusercontent.com/17395556/151942910-955be202-cfee-42fe-b9bc-e428f7640b41.png)

Visible after cutscene though
![image](https://user-images.githubusercontent.com/17395556/151942970-55236242-c83f-4140-aaff-a506b39b1499.png)

**Comment by mrneo240** [comment]
Investigating but its an odd issue to say the least

**Comment by Zero3K** [comment]
Maybe its the same issue that #69 is fixing for another NPC.

**Comment by mrneo240** [comment]
I dont believe that fixes this particular issue, at least not locally for me.
[https://i.imgur.com/BSkneTQ.png](https://i.imgur.com/BSkneTQ.png)

**Comment by mrneo240** [comment]
![https://cdn.discordapp.com/attachments/938481285804994631/939976909784223804/unknown.png](https://cdn.discordapp.com/attachments/938481285804994631/939976909784223804/unknown.png)

**Comment by mrneo240** [comment]
a potential working fix is being experimented with

**Comment by Zero3K** [comment]
This has been fixed thanks to mrneo240's fixes which have been added as commit https://github.com/blawar/ooot/commit/d1a07b2519fd2112e465504ddc62afb80f63652d.
