### ISSUE TITLE
Player gets stuck in kokiri forest tunnel in 60FPS

### ISSUE THREAD

**Issue by blawar** [blawar/ooot#245]
Player gets stuck and can no longer move when crawling in the tunnel in kokiri forest in 60FPS:

![image](https://user-images.githubusercontent.com/10227949/161802360-b35f7e04-63fa-476b-85d5-9e162a9309b7.png)

**Comment by thomas992** [comment]
https://github.com/blawar/ooot/blob/51bae57631e48313d648a6019982e79e8d6bdea0/src/code/z_actor.cpp#L910

somewhere the variable for Link actor was severed I suspect?
