### ISSUE TITLE
Improve Render Distance

### ISSUE THREAD

**Issue by VioBeeyo** [blawar/ooot#25]
NPCs such as the Chicken in Kakariko Village will visibly poof out of existence when passing a certain distance. While this is probably normal behavior on the N64, it could probably be improved for the PC Port

https://user-images.githubusercontent.com/95020200/151985706-bc3757bb-480f-4a6b-9b87-2d3dba5376fe.mp4

The same thing seems to also affect Objects, the Sign and wooden logs at the well seem to be affected too.

**Comment by DaMarkov** [comment]
I have submitted PR #47 which should fix this issue.
The PR adds a compiler flag that disables culling for all actors.

**Comment by blawar** [comment]
Fixed by @DaMarkov , thank you!
