### ISSUE TITLE
ESS rotation is slower in 60 FPS

### ISSUE THREAD

**Issue by Lehpumeh** [blawar/ooot#251]
## Current Behavior

When doing ESS, Link will rotate slower than he would in 20 FPS. Makes doing ESS/HESS harder to maneuver around sharp corners because you can't rotate fast enough.

https://user-images.githubusercontent.com/99471756/162851783-24a5a029-8343-4fad-8c6e-5a9977ff3bbd.mp4

**Comment by Lehpumeh** [comment]
Seems to be fixed.

**Comment by blawar** [comment]
Thank you for following up!
