### ISSUE TITLE
Links goes through some fences and runs up ledges in 60FPS

### ISSUE THREAD

**Issue by Lehpumeh** [blawar/ooot#252]
## Current Behavior

Link will go through some fences that he can't climb and through invisible walls in the shooting mini game. Also runs over edges he would normally do a small jump for.

https://user-images.githubusercontent.com/99471756/162854572-a176c292-0938-4643-83a4-53d76ba93d72.mp4

**Comment by Mic601** [comment]
Sounds like an improvement not gonna lie

**Comment by blawar** [comment]
should be fixed
