### ISSUE TITLE
Skybox Seams are visible in Hyrule Field

### ISSUE THREAD

**Issue by VioBeeyo** [blawar/ooot#26]
While talking to the Owl in Hyrule Field you can very clearly see the seams that connect each wall and the ceiling of the Skybox.
![FKhFvlBXwAcHQn7](https://user-images.githubusercontent.com/95020200/151992307-689c0f14-fc38-4b50-a583-93ee65fe3f9e.jpg)

**Comment by blawar** [comment]
this is not an error, that is how it is on the N64 and in emulators as well.

**Comment by Zero3K** [comment]
Could it still be fixed?
