### ISSUE TITLE
License exemption incompatible with GLideN64

### ISSUE THREAD

**Issue by Uklosk** [blawar/ooot#27]
GLideN64 license is a pure GPLv2 without linking exception, so that makes Open Ocarina GPLv2 without any possible exceptions.

Also if anyone forks this project and doesn't want to keep that exemption, all their changes can't be contributed back to this repository, because GPLv2 won't allow it.

**Comment by blawar** [comment]
The exception applies to this repository only, not GlideN64.  GlideN64 has its own repository with its own license: https://github.com/blawar/GLideN64/blob/master/LICENSE

In the situation you speak of, the users are free to not link gliden64 and use another renderer.  There is a graphics API that allows another renderer to be plugged in, and I do indeed plan to support multiple renderers in the future.

Not withstanding the fact that what people want to--or do not want to--agree to after forking is a personal choice of their own.  If they do not like the terms, they do not have to fork it.
