### ISSUE TITLE
Fairy Fountain hole in Lost woods

### ISSUE THREAD

**Issue by XS09-dev** [blawar/ooot#275]
So, Every time you go into the fairy fountain in lost woods and exit you fly in the air and go straight back in, You need to target and do a jump slash to stop going in and out.

## Current Behavior
What I just explained still happens.

## Expected Behavior
You get shot out of the hole up and straight forward near the ladder.

## Possible Solution
Fix the position of link when getting shot out of the hole.

## Context (Environment)
Needed to jump slash every time to get out of the hole which hits you back near the hole which you then have a chance of going back in the hole.

**Comment by blawar** [comment]
unable to reproduce, might have already been fixed in another bf.
