### ISSUE TITLE
Multi: Forest Temple room before boss battle wall collision. | Forest Temple room before boss battle will shift then shift back to the position it once was.

### ISSUE THREAD

**Issue by XS09-dev** [blawar/ooot#277]
1. So in that room where you push the wall and it shifts there is a wall problem, Where you go through the wall and jump to your demise, this also allows you to skip the puzzle.
2.  In the exact same room whenever you push the wall it shifts than the cam glitches and either one or 2 things happens it skips  push or shifts back to the original place.

## Current Behavior
1. What I explained.
2. What I explained.

## Expected Behavior
1. There should be collision and shouldn't be able to walk out.
2. It shifts once without glitch and skipping a shift or going back to the first place.

## Possible Solution
1. Add collision.
2. I have no idea. But it could be a problem with how the wall gets moved, aka the code that calls the action of shifting when link moves it.

## Context (Environment)
This affects the game in Two ways: One you can use the wall shift but it will take literally forever to land on what you need it to land on and two You can easily just skip the puzzle by pushing it once than going out of the wall and jumping to the gate that blocks the boss door.

**Comment by Lehpumeh** [comment]
Video of the bug. Happens in 60FPS. Fine in 20FPS

https://user-images.githubusercontent.com/99471756/163657948-2f5d3c7e-7f7d-499a-a0cc-877c67d6dc21.mp4

**Comment by blawar** [comment]
should be fixed, re-open if the issue persists.
