### ISSUE TITLE
Crash after pausing, navigating to "Equipment" menu, closing the menu, then reopening it

### ISSUE THREAD

**Issue by Karma-Enthusiast** [blawar/ooot#279]
After opening the pause menu, navigating to the "Equipment" screen, closing the pause menu, then re-entering it, the game will crash. 

## Current Behavior
The game crashes instantly upon re-opening the menu _if_ you went to the "Equipment" screen _beforehand._ 

## Expected Behavior
The game should allow you to enter the pause menu as normal.

## Example
I have no idea how to embed YouTube videos in GitHub, and I can't upload the video I took directly because it's too big; **this probably won't open in a new link**, but here's a video: https://youtu.be/RMAwO29Tazw

## Possible Solution
No clue. However it _isn't_ caused by:

1. FPS - The issue occurs at all FPS settings (at least for me).
2. Location - This was happening to me yesterday in Kokiri Forest when swapping from no shield to the Deku Shield, and also happened when I tested this outside of Jabu Jabu (in Zora's Fountain). 
3. Inventory - This was happening early on in the game too (I didn't realize what the crash was caused by at the time).  

## Context
I have no texture packs or other mods installed, and I'm using the Release-Win32 build. I updated the port about 2 minutes ago, but this was still happening before the update. If any other info is needed let me know.

**Comment by Karma-Enthusiast** [comment]
Also, just tested the following, which did _not_ cause a crash:

1. Opening the pause menu.
2. Navigating to the "Equipment" screen.
3. Closing the pause menu.
4. Leaving Jabu Jabu into Zora's Fountain.
5. Reopening the pause menu (which defaults to the "Equipment" menu). 

I guess leaving an area "wipes" whatever is causing the issue? That's my best guess.

**Comment by blawar** [comment]
fixed
