### ISSUE TITLE
60fps: After beating from what I can tell most bosses you just hover and get softlocked

### ISSUE THREAD

**Issue by XS09-dev** [blawar/ooot#281]
After beating some bosses in 60fps you get soft locked (aka hovering in one place) when getting teleported back to the start of the dungeon until you turn on 20fps.

## Current Behavior
What I explained.

## Expected Behavior
You should slowly float down onto the ground.

## Possible Solution
Fix the way link gets teleported..

## Context (Environment)
Affects the game by soft locking you in 60fps.

**Comment by blawar** [comment]
fixed
