### ISSUE TITLE
60 FPS Broken Frogs in Zora's River

### ISSUE THREAD

**Issue by Chadlight** [blawar/ooot#286]
The frogs in Child era Zora's River do not jump on or off the log at 60 FPS, the game will softlock

## Current Behavior
Frogs do not hop on the log after using Ocarina on stump

## Expected Behavior
Frogs should hop on log

## Possible Solution
The 60 FPS probably breaks the frog jumping animation 

## Steps to Reproduce
1. Go to Zora's River and try to call the frogs with Ocarina ( Save your game before trying this ! )

**Comment by blawar** [comment]
fixed
