### ISSUE TITLE
60 FPS Link's animation delay underwater

### ISSUE THREAD

**Issue by Chadlight** [blawar/ooot#287]
When Link goes up to the surface after diving underwater, he will reach the surface of the water but yet his body will still be facing down and there is a strange delay as he slowly turns upside 

## Current Behavior
Link struggles to change direction underwater at 60 FPS

## Expected Behavior
When Link hits the bottom of his dive he should flip around and start swimming upwards instead of floating up while facing down like a corpse

## Possible Solution
Have Link start his swim upwards animation when colliding with the floor or timer on dive runs out or anytime the player quits diving

## Steps to Reproduce
1. Dive underwater
2. Notice how long Link takes to go into his swim upward animation from his dive animation

Video of problem, go to timestamp 8:47

https://youtu.be/BiQrNDB9wEo?t=528

**Comment by XS09-dev** [comment]
Hey btw make sure to see if there is any issues created about this already.

**Comment by blawar** [comment]
fixed
