### ISSUE TITLE
60 FPS bottom of the well crawl space

### ISSUE THREAD

**Issue by XS09-dev** [blawar/ooot#288]
In 60 FPS when you go into the crawl space and exit it, You get put back in the crawl space and then you stand up where you get stuck.

## Current Behavior
What I said above.

## Expected Behavior
You go in and out simple.

## Context (Environment)
Affects progress in 60 fps.

![Base Profile Screenshot 2022 04 18 - 10 43 16 98](https://user-images.githubusercontent.com/81271362/163824892-142acaff-a2a7-4418-9d06-7b48ab9501f3.png)

**Comment by Chadlight** [comment]
This is for every single crawl space not just BoTW, and as of now the solution is to swing your sword after you get to the end and Link will get unstuck

**Comment by XS09-dev** [comment]
> This is for every single crawl space not just BoTW, and as of now the solution is to swing your sword after you get to the end and Link will get unstuck

Really? I never actually had the problem till BoTW

**Comment by blawar** [comment]
this is temp fixed by forcing the framerate down to 20FPS during the crawl space.
