### ISSUE TITLE
Change/Remove License, consider name change (OoT is not FOSS)

### ISSUE THREAD

**Issue by MotoLegacy** [blawar/ooot#29]
This repository/source code is currently listed as being licensed under [GPLv2](https://www.gnu.org/licenses/old-licenses/gpl-2.0.en.html). I do not believe this is applicable to this project. Ocarina of Time is not free and open source software, nor was it ever designed to be.

While clean (or near clean) reverse engineering of software is a legal gray area in most if not all regions, doing so does not permit the developers or engineers to apply a permissive license, if any license at all.

[RE3, the recently DMCA'd reimplementation of the 3D Grand Theft Auto trilogy](https://www.eurogamer.net/articles/2021-10-02-gta-reverse-engineering-fan-projects-pulled-offline-for-a-second-time-after-yet-another-take-two-takedown) put this best by saying:
`We don't feel like we're in a position to give this code a license.` 

This also means the OoT reversing effort and all of its derivatives (including this one) are technically **not** open source software at all, and should not be advertised as such. While the source code is available and modding is implied to be encouraged, in no way were the rights waived from anyone, be that the team who has reversed OoT or even Nintendo themselves. For this reason it might be a good idea to remove the "Open" branding of this repository name and README title.

Even disregarding the legal issues with licensing reversed code, it is generally bad practice to re-license software without the consent of every project contributor. Here is good insight regarding this issue: https://opensource.guide/legal/#what-if-i-want-to-change-the-license-of-my-project

**Comment by jdroo** [comment]
Being none of Nintendo's code/assets exists in this software here, does that even apply?

**Comment by LordVulkan** [comment]
> Being none of Nintendo's code/assets exists in this software here, does that even apply?

Even if it does not apply, the decompilation project does not have a license, so I doubt it can be magically converted to GPLv2 without all the original contributors consent:
https://github.com/zeldaret/oot

**Comment by TheMrIron2** [comment]
Vulkan and Moto are right - even if this project was considered completely clean and derivative and contained no Nintendo code (a murky argument, given the whole project is built on decompiled Nintendo code), OpenOOT is built on the zeldaret repository, which is not licensed.

Even if you were to reason you could licence reconstructed Nintendo code, this project is built on another team's work and it requires the original team's consent to be relicensed. The project itself can still exist alongside the decompilation, of course, but it doesn't have the right to re-license the project it is based on.
Hopefully a simple issue that the developers can fix by either discussing licensing with the zeldaret team or dropping the GPLv2 license.

**Comment by LordVulkan** [comment]
So, to wrap it up.

- Decompilation project doesn't have a license, so it can't be forked and relicensed as GPL v2 without all the contributors authorization.
- GLideN64 is GPLv2 without linking exception, so it only can be linked from GPL v2 projects.

I think this project can't use GLideN64 legally, it should ditch GPL v2 license and use something with a more permissive license like n64-fast3d-engine (the same SM64 Port does): https://github.com/Emill/n64-fast3d-engine/blob/master/LICENSE.txt

**Comment by blawar** [comment]
Having no license what so ever is not an option.  The license only applies to code written after it was formed from the upstream repo.  The readme will be updated to more accurately reflect this.
