### ISSUE TITLE
Great Fairy near Ganons tower.

### ISSUE THREAD

**Issue by XS09-dev** [blawar/ooot#291]
If you go to the Great Fairy at ganons tower and throw the pillar the controls get locked.

## Current Behavior
What I said above.

## Expected Behavior
You grab a big boulder of some sorts and link plays a throwing animation, then you go into it without a control problem/

## Context (Environment)
Can't get the better defense meaning you take more damage from ganon unless on 20 fps.

**Comment by Lehpumeh** [comment]
Need golden gauntlets to throw the boulder, but specifically in 60FPS the camera goes fast and when he throws the boulder the controls are locked so it's still a  problem. 

https://user-images.githubusercontent.com/99471756/163879961-d30c3d47-b91d-43c3-9bb0-898c7360af9e.mp4

20FPS works as intended.

**Comment by XS09-dev** [comment]
My b. I forgot you need gold gauntlets but yes 60fps freezes so I'll edit rq

**Comment by blawar** [comment]
fixed
