### ISSUE TITLE
Blue Bubble enemy cannot die

### ISSUE THREAD

**Issue by Johnuca** [blawar/ooot#297]
The blue bubble enemy lies on the ground motionless whenever killed, technically still counted as alive. This halts progression entirely, since you need to kill a blue bubble in order to progress through the forest temple

## Current Behavior
 It lies still, unable to be killed

## Expected Behavior
It should die normally

## Possible Solution
 I have no idea

## Steps to Reproduce

1. Go to a Blue Bubble (forest temple is where I found it)
2. Use hook shot to stun it
3. Use sword to finish it off
4. Observe

## Context (Environment)

 It doesn’t let me beat the forest temple :(

**Comment by blawar** [comment]
Is this a 60fps bug? Or does it do it in 20fps as well?

**Comment by Lehpumeh** [comment]
20FPS is fine, but in 60FPS if you don't one shot it with a jump slash it will just slide on the floor and never be able to be hit again.

https://user-images.githubusercontent.com/99471756/164347056-09b1c7f9-b4d7-4fbf-a934-f2f174f97b5e.mp4

**Comment by blawar** [comment]
fixed
