### ISSUE TITLE
Spin Attack Causes Black Background

### ISSUE THREAD

**Issue by MatttyMattHew** [blawar/ooot#3]
Charging spin and stick spin both cause the issue.

![image](https://user-images.githubusercontent.com/98795913/151914961-b8d95af6-f2fc-42a7-bfbc-81551dbac08d.png)

**Comment by DaMarkov** [comment]
Framebuffer emulation issue. Will be fixed once merged.
I assume this looks correct:
![image](https://user-images.githubusercontent.com/35939509/153031205-2a9253cc-2210-4c18-b536-6988de89557b.png)

**Comment by Zero3K** [comment]
It has been fixed thanks to commit https://github.com/blawar/ooot/commit/ac2b25f6a5030a23867a68e989b104c2af11d340.
