### ISSUE TITLE
Bugs in a bottle 60FPS issues

### ISSUE THREAD

**Issue by Lehpumeh** [blawar/ooot#300]
## Current Behavior

When you dump bugs, they will fall slowly. 

When they land, they burrow into the ground much faster than normal
## Steps to Reproduce

1. Dump bugs

60FPS vs 20FPS

https://user-images.githubusercontent.com/99471756/164592717-45851306-1a57-44e0-86c7-6f531c46d152.mp4

**Comment by blawar** [comment]
should be fixed, re-open if issue persists.
