### ISSUE TITLE
Kokiri Shop background is  glitched

### ISSUE THREAD

**Issue by topkeksphagetti** [blawar/ooot#31]
![image](https://user-images.githubusercontent.com/15426253/152035125-67116f24-7976-4378-8bb8-3dd834a12a77.png)

**Comment by VioBeeyo** [comment]
Duplicate issue of https://github.com/blawar/ooot/issues/10

**Comment by blawar** [comment]
This should be fixed in master.  You will need to run convert_assets.py on master to re-extract the jpegs.
