### ISSUE TITLE
60 FPS, unable to climb down ladder from Link's house.

### ISSUE THREAD

**Issue by e2zippo** [blawar/ooot#310]
Link is unable to climb down the ladder from his house in 60 FPS, if you're walking fast enough or run you just jump down.
Even if you walk as slowly as possible, he just hangs from the ledge, he's unable to climb the ladder.

## Current Behavior
Link is unable to climb down the ladder from his house in 60 FPS, if you're walking fast enough or run you just jump down.
Even if you walk as slowly as possible, he just hangs from the ledge, he's unable to climb the ladder.

## Expected Behavior
Link should grab the ladder and start climbing down .
This works in in 20 fps, but not 60.

## Detailed Description
This was tried with a build from 29th or April.

Video showing the problem.
https://www.youtube.com/watch?v=BV0T68R8TBU

**Comment by blawar** [comment]
should be fixed, re-open if the issue persists.
