### ISSUE TITLE
60 FPS: Link walks over chests instead of stopping in front of them.

### ISSUE THREAD

**Issue by e2zippo** [blawar/ooot#311]
When using 60 FPS links walks over the chests in the house in kokiri forest instead of stopping in front of them.

Current Behavior
When using 60 FPS links walks over the chests in the house in kokiri forest instead of stopping in front of them.

Expected Behavior
Link should not be able to walk over / through the chests, he should stop in front of them.
It works in 20 fps but not 60.

Detailed Description
This was tried with a build from 29th or April.

Video showing the problem.
https://youtu.be/ZMa5PkZuW_Y

**Comment by blawar** [comment]
should be fixed.
