### ISSUE TITLE
The game does not open.

### ISSUE THREAD

**Issue by Lufims** [blawar/ooot#312]
## Current Behavior
I click on the executable and the game crashes

## Expected Behavior
Open the game

## Possible Solution
I think it's because the opengl or the directx, i have opengl 1.4 and directx 11, so if think if that is the problem the fix is to add compatibility to this opengl and directx. 

## Steps to Reproduce

1.Click on the game executable
2.Don't have more steps
3.
4.

## Context (Environment)
 I can't play the game, and i want to play the game

## Detailed Description
Exception without treatment in 0x7406CB59 in OOT.exe: 0xC0000005: access violation reading location 0x00000000.

**Comment by nitrostemp** [comment]
gonna need some hardware info.

**Comment by Lufims** [comment]
> gonna need some hardware info.

Sorry for the delay

------------------
System Information
------------------
Time of this report: 4/30/2022, 11:05:24
       Machine name: USER
   Operating System: Windows 7 Professional 64-bit (6.1, Build 7601) Service Pack 1 (7601.win7sp1_ldr_escrow.220222-1157)
           Language: Portuguese (Regional Setting: Portuguese)
System Manufacturer: ECS
       System Model: 945GCT-M2
               BIOS: Default System BIOS
          Processor: Pentium(R) Dual-Core  CPU      E5300  @ 2.60GHz (2 CPUs), ~2.6GHz
             Memory: 4096MB RAM
Available OS Memory: 3320MB RAM
          Page File: 1346MB used, 5290MB available
        Windows Dir: C:\Windows
    DirectX Version: DirectX 11
DX Setup Parameters: Not found
   User DPI Setting: Using System DPI
 System DPI Setting: 96 DPI (100 percent)
    DWM DPI Scaling: Disabled
     DxDiag Version: 6.01.7601.17514 32bit Unicode

------------
DxDiag Notes
------------
      Display Tab 1: No problems found.
        Sound Tab 1: No problems found.
        Sound Tab 2: No problems found.
          Input Tab: No problems found.

--------------------
DirectX Debug Levels
--------------------
Direct3D:    0/4 (retail)
DirectDraw:  0/4 (retail)
DirectInput: 0/5 (retail)
DirectMusic: 0/5 (retail)
DirectPlay:  0/9 (retail)
DirectSound: 0/5 (retail)
DirectShow:  0/6 (retail)

---------------
Display Devices
---------------
          Card name: Intel(R) 82945G Express Chipset Family
       Manufacturer: Intel Corporation
          Chip type: Intel(R) 82945G Express Chipset Family
           DAC type: Internal
         Device Key: Enum\PCI\VEN_8086&DEV_2772&SUBSYS_26331019&REV_02
     Display Memory: 256 MB
   Dedicated Memory: 0 MB
      Shared Memory: 256 MB
       Current Mode: 1280 x 768 (32 bit) (60Hz)
       Monitor Name: Monitor Genérico não PnP
      Monitor Model: unknown
         Monitor Id: 
        Native Mode: unknown
        Output Type: HD15
        Driver Name: igdumd64.dll
Driver File Version: 8.14.0010.1930 (English)
     Driver Version: 8.15.10.1930
        DDI Version: 9Ex
       Driver Model: WDDM 1.0
  Driver Attributes: Final Retail
   Driver Date/Size: 9/23/2009 19:22:58, 5472256 bytes
        WHQL Logo'd: n/a
    WHQL Date Stamp: n/a
  Device Identifier: {D7B78E66-6432-11CF-2374-3906A3C2C535}
          Vendor ID: 0x8086
          Device ID: 0x2772
          SubSys ID: 0x26331019
        Revision ID: 0x0002
 Driver Strong Name: oem86.inf:Intel.Mfg.NTamd64:i945G0:8.15.10.1930:pci\ven_8086&dev_2772
     Rank Of Driver: 00F42001
        Video Accel: ModeMPEG2_A ModeMPEG2_C 
   Deinterlace Caps: {AEDC1D5D-8546-440E-AAB2-B69FA725AF82}: Format(In/Out)=(YUY2,YUY2) Frames(Prev/Fwd/Back)=(0,0,1) Caps=VideoProcess_YUV2RGB VideoProcess_StretchX VideoProcess_StretchY VideoProcess_AlphaBlend DeinterlaceTech_FieldAdaptive 
                     {335AA36E-7884-43A4-9C91-7F87FAF3E37E}: Format(In/Out)=(YUY2,YUY2) Frames(Prev/Fwd/Back)=(0,0,0) Caps=VideoProcess_YUV2RGB VideoProcess_StretchX VideoProcess_StretchY VideoProcess_AlphaBlend DeinterlaceTech_BOBVerticalStretch 
                     {5A54A0C9-C7EC-4BD9-8EDE-F3C75DC4393B}: Format(In/Out)=(YUY2,YUY2) Frames(Prev/Fwd/Back)=(0,0,0) Caps=VideoProcess_YUV2RGB VideoProcess_StretchX VideoProcess_StretchY VideoProcess_AlphaBlend 
                     {AEDC1D5D-8546-440E-AAB2-B69FA725AF82}: Format(In/Out)=(UYVY,YUY2) Frames(Prev/Fwd/Back)=(0,0,1) Caps=VideoProcess_YUV2RGB VideoProcess_StretchX VideoProcess_StretchY VideoProcess_AlphaBlend DeinterlaceTech_FieldAdaptive 
                     {335AA36E-7884-43A4-9C91-7F87FAF3E37E}: Format(In/Out)=(UYVY,YUY2) Frames(Prev/Fwd/Back)=(0,0,0) Caps=VideoProcess_YUV2RGB VideoProcess_StretchX VideoProcess_StretchY VideoProcess_AlphaBlend DeinterlaceTech_BOBVerticalStretch 
                     {5A54A0C9-C7EC-4BD9-8EDE-F3C75DC4393B}: Format(In/Out)=(UYVY,YUY2) Frames(Prev/Fwd/Back)=(0,0,0) Caps=VideoProcess_YUV2RGB VideoProcess_StretchX VideoProcess_StretchY VideoProcess_AlphaBlend 
                     {AEDC1D5D-8546-440E-AAB2-B69FA725AF82}: Format(In/Out)=(YV12,YUY2) Frames(Prev/Fwd/Back)=(0,0,1) Caps=VideoProcess_YUV2RGB VideoProcess_StretchX VideoProcess_StretchY VideoProcess_AlphaBlend DeinterlaceTech_FieldAdaptive 
                     {335AA36E-7884-43A4-9C91-7F87FAF3E37E}: Format(In/Out)=(YV12,YUY2) Frames(Prev/Fwd/Back)=(0,0,0) Caps=VideoProcess_YUV2RGB VideoProcess_StretchX VideoProcess_StretchY VideoProcess_AlphaBlend DeinterlaceTech_BOBVerticalStretch 
                     {5A54A0C9-C7EC-4BD9-8EDE-F3C75DC4393B}: Format(In/Out)=(YV12,YUY2) Frames(Prev/Fwd/Back)=(0,0,0) Caps=VideoProcess_YUV2RGB VideoProcess_StretchX VideoProcess_StretchY VideoProcess_AlphaBlend 
                     {AEDC1D5D-8546-440E-AAB2-B69FA725AF82}: Format(In/Out)=(NV12,YUY2) Frames(Prev/Fwd/Back)=(0,0,1) Caps=VideoProcess_YUV2RGB VideoProcess_StretchX VideoProcess_StretchY VideoProcess_AlphaBlend DeinterlaceTech_FieldAdaptive 
                     {335AA36E-7884-43A4-9C91-7F87FAF3E37E}: Format(In/Out)=(NV12,YUY2) Frames(Prev/Fwd/Back)=(0,0,0) Caps=VideoProcess_YUV2RGB VideoProcess_StretchX VideoProcess_StretchY VideoProcess_AlphaBlend DeinterlaceTech_BOBVerticalStretch 
                     {5A54A0C9-C7EC-4BD9-8EDE-F3C75DC4393B}: Format(In/Out)=(NV12,YUY2) Frames(Prev/Fwd/Back)=(0,0,0) Caps=VideoProcess_YUV2RGB VideoProcess_StretchX VideoProcess_StretchY VideoProcess_AlphaBlend 
                     {AEDC1D5D-8546-440E-AAB2-B69FA725AF82}: Format(In/Out)=(IMC1,YUY2) Frames(Prev/Fwd/Back)=(0,0,1) Caps=VideoProcess_YUV2RGB VideoProcess_StretchX VideoProcess_StretchY VideoProcess_AlphaBlend DeinterlaceTech_FieldAdaptive 
                     {335AA36E-7884-43A4-9C91-7F87FAF3E37E}: Format(In/Out)=(IMC1,YUY2) Frames(Prev/Fwd/Back)=(0,0,0) Caps=VideoProcess_YUV2RGB VideoProcess_StretchX VideoProcess_StretchY VideoProcess_AlphaBlend DeinterlaceTech_BOBVerticalStretch 
                     {5A54A0C9-C7EC-4BD9-8EDE-F3C75DC4393B}: Format(In/Out)=(IMC1,YUY2) Frames(Prev/Fwd/Back)=(0,0,0) Caps=VideoProcess_YUV2RGB VideoProcess_StretchX VideoProcess_StretchY VideoProcess_AlphaBlend 
                     {AEDC1D5D-8546-440E-AAB2-B69FA725AF82}: Format(In/Out)=(IMC2,YUY2) Frames(Prev/Fwd/Back)=(0,0,1) Caps=VideoProcess_YUV2RGB VideoProcess_StretchX VideoProcess_StretchY VideoProcess_AlphaBlend DeinterlaceTech_FieldAdaptive 
                     {335AA36E-7884-43A4-9C91-7F87FAF3E37E}: Format(In/Out)=(IMC2,YUY2) Frames(Prev/Fwd/Back)=(0,0,0) Caps=VideoProcess_YUV2RGB VideoProcess_StretchX VideoProcess_StretchY VideoProcess_AlphaBlend DeinterlaceTech_BOBVerticalStretch 
                     {5A54A0C9-C7EC-4BD9-8EDE-F3C75DC4393B}: Format(In/Out)=(IMC2,YUY2) Frames(Prev/Fwd/Back)=(0,0,0) Caps=VideoProcess_YUV2RGB VideoProcess_StretchX VideoProcess_StretchY VideoProcess_AlphaBlend 
                     {AEDC1D5D-8546-440E-AAB2-B69FA725AF82}: Format(In/Out)=(IMC3,YUY2) Frames(Prev/Fwd/Back)=(0,0,1) Caps=VideoProcess_YUV2RGB VideoProcess_StretchX VideoProcess_StretchY VideoProcess_AlphaBlend DeinterlaceTech_FieldAdaptive 
                     {335AA36E-7884-43A4-9C91-7F87FAF3E37E}: Format(In/Out)=(IMC3,YUY2) Frames(Prev/Fwd/Back)=(0,0,0) Caps=VideoProcess_YUV2RGB VideoProcess_StretchX VideoProcess_StretchY VideoProcess_AlphaBlend DeinterlaceTech_BOBVerticalStretch 
                     {5A54A0C9-C7EC-4BD9-8EDE-F3C75DC4393B}: Format(In/Out)=(IMC3,YUY2) Frames(Prev/Fwd/Back)=(0,0,0) Caps=VideoProcess_YUV2RGB VideoProcess_StretchX VideoProcess_StretchY VideoProcess_AlphaBlend 
                     {AEDC1D5D-8546-440E-AAB2-B69FA725AF82}: Format(In/Out)=(IMC4,YUY2) Frames(Prev/Fwd/Back)=(0,0,1) Caps=VideoProcess_YUV2RGB VideoProcess_StretchX VideoProcess_StretchY VideoProcess_AlphaBlend DeinterlaceTech_FieldAdaptive 
                     {335AA36E-7884-43A4-9C91-7F87FAF3E37E}: Format(In/Out)=(IMC4,YUY2) Frames(Prev/Fwd/Back)=(0,0,0) Caps=VideoProcess_YUV2RGB VideoProcess_StretchX VideoProcess_StretchY VideoProcess_AlphaBlend DeinterlaceTech_BOBVerticalStretch 
                     {5A54A0C9-C7EC-4BD9-8EDE-F3C75DC4393B}: Format(In/Out)=(IMC4,YUY2) Frames(Prev/Fwd/Back)=(0,0,0) Caps=VideoProcess_YUV2RGB VideoProcess_StretchX VideoProcess_StretchY VideoProcess_AlphaBlend 
       D3D9 Overlay: Not Supported
            DXVA-HD: Not Supported
       DDraw Status: Enabled
         D3D Status: Enabled
         AGP Status: Enabled

-------------
Sound Devices
-------------
            Description: Alto-falantes (Dispositivo de High Definition Audio)
 Default Sound Playback: Yes
 Default Voice Playback: Yes
            Hardware ID: HDAUDIO\FUNC_01&VEN_8384&DEV_7682&SUBSYS_10192633&REV_1036
        Manufacturer ID: 1
             Product ID: 65535
                   Type: WDM
            Driver Name: HdAudio.sys
         Driver Version: 6.01.7601.24519 (Portuguese)
      Driver Attributes: Final Retail
            WHQL Logo'd: n/a
          Date and Size: 3/18/2022 03:56:10, 350208 bytes
            Other Files: 
        Driver Provider: Microsoft
         HW Accel Level: Basic
              Cap Flags: 0x0
    Min/Max Sample Rate: 0, 0
Static/Strm HW Mix Bufs: 0, 0
 Static/Strm HW 3D Bufs: 0, 0
              HW Memory: 0
       Voice Management: No
 EAX(tm) 2.0 Listen/Src: No, No
   I3DL2(tm) Listen/Src: No, No
Sensaura(tm) ZoomFX(tm): No

            Description: Áudio Digital (S/PDIF) (Dispositivo de High Definition Audio)
 Default Sound Playback: No
 Default Voice Playback: No
            Hardware ID: HDAUDIO\FUNC_01&VEN_8384&DEV_7682&SUBSYS_10192633&REV_1036
        Manufacturer ID: 1
             Product ID: 65535
                   Type: WDM
            Driver Name: HdAudio.sys
         Driver Version: 6.01.7601.24519 (Portuguese)
      Driver Attributes: Final Retail
            WHQL Logo'd: n/a
          Date and Size: 3/18/2022 03:56:10, 350208 bytes
            Other Files: 
        Driver Provider: Microsoft
         HW Accel Level: Basic
              Cap Flags: 0x0
    Min/Max Sample Rate: 0, 0
Static/Strm HW Mix Bufs: 0, 0
 Static/Strm HW 3D Bufs: 0, 0
              HW Memory: 0
       Voice Management: No
 EAX(tm) 2.0 Listen/Src: No, No
   I3DL2(tm) Listen/Src: No, No
Sensaura(tm) ZoomFX(tm): No

---------------------
Sound Capture Devices
---------------------
            Description: Microfone (Dispositivo de High Definition Audio)
  Default Sound Capture: Yes
  Default Voice Capture: Yes
            Driver Name: HdAudio.sys
         Driver Version: 6.01.7601.24519 (Portuguese)
      Driver Attributes: Final Retail
          Date and Size: 3/18/2022 03:56:10, 350208 bytes
              Cap Flags: 0x0
           Format Flags: 0x0

-------------------
DirectInput Devices
-------------------
      Device Name: Mouse
         Attached: 1
    Controller ID: n/a
Vendor/Product ID: n/a
        FF Driver: n/a

      Device Name: Teclado
         Attached: 1
    Controller ID: n/a
Vendor/Product ID: n/a
        FF Driver: n/a

      Device Name: CASUE USB Keyboard
         Attached: 1
    Controller ID: 0x0
Vendor/Product ID: 0x2A7A, 0x9A18
        FF Driver: n/a

      Device Name: CASUE USB Keyboard
         Attached: 1
    Controller ID: 0x0
Vendor/Product ID: 0x2A7A, 0x9A18
        FF Driver: n/a

Poll w/ Interrupt: No

-----------
USB Devices
-----------
+ USB Root Hub
| Vendor/Product ID: 0x8086, 0x27CB
| Matching Device ID: usb\root_hub
| Service: usbhub

----------------
Gameport Devices
----------------

------------
PS/2 Devices
------------
+ Dispositivo de teclado HID
| Vendor/Product ID: 0x2A7A, 0x9A18
| Matching Device ID: hid_device_system_keyboard
| Service: kbdhid
| 
+ Terminal Server Keyboard Driver
| Matching Device ID: root\rdp_kbd
| Upper Filters: kbdclass
| Service: TermDD
| 
+ Mouse compatível com HID
| Vendor/Product ID: 0x10C4, 0x8108
| Matching Device ID: hid_device_system_mouse
| Service: mouhid
| 
+ Terminal Server Mouse Driver
| Matching Device ID: root\rdp_mou
| Upper Filters: mouclass
| Service: TermDD

------------------------
Disk & DVD/CD-ROM Drives
------------------------
      Drive: C:
 Free Space: 340.7 GB
Total Space: 476.4 GB
File System: NTFS
      Model: WDC WD5000AAKX-00U6AA0 ATA Device

--------------
System Devices
--------------
     Name: Intel(R) 82801G (ICH7 Family) USB Universal Host Controller - 27CA
Device ID: PCI\VEN_8086&DEV_27CA&SUBSYS_26331019&REV_01\3&11583659&0&EA
   Driver: n/a

     Name: Realtek RTL8139/810x Family Fast Ethernet NIC
Device ID: PCI\VEN_10EC&DEV_8139&SUBSYS_211C1462&REV_10\4&5D52D80&0&28F0
   Driver: n/a

     Name: Intel(R) 82801G (ICH7 Family) USB Universal Host Controller - 27C9
Device ID: PCI\VEN_8086&DEV_27C9&SUBSYS_26331019&REV_01\3&11583659&0&E9
   Driver: n/a

     Name: Intel(R) 82801G (ICH7 Family) USB Universal Host Controller - 27C8
Device ID: PCI\VEN_8086&DEV_27C8&SUBSYS_26331019&REV_01\3&11583659&0&E8
   Driver: n/a

     Name: Intel(R) 82801G (ICH7 Family) Ultra ATA Storage Controllers - 27DF
Device ID: PCI\VEN_8086&DEV_27DF&SUBSYS_26331019&REV_01\3&11583659&0&F9
   Driver: n/a

     Name: Intel(R) 82801GB/GR/GH (ICH7 Family) Serial ATA Storage Controller - 27C0
Device ID: PCI\VEN_8086&DEV_27C0&SUBSYS_26331019&REV_01\3&11583659&0&FA
   Driver: n/a

     Name: Intel(R) 82801G (ICH7 Family) SMBus Controller - 27DA
Device ID: PCI\VEN_8086&DEV_27DA&SUBSYS_26331019&REV_01\3&11583659&0&FB
   Driver: n/a

     Name: Intel(R) 82801GB/GR (ICH7 Family) LPC Interface Controller - 27B8
Device ID: PCI\VEN_8086&DEV_27B8&SUBSYS_26331019&REV_01\3&11583659&0&F8
   Driver: n/a

     Name: Controlador de High Definition Audio
Device ID: PCI\VEN_8086&DEV_27D8&SUBSYS_26331019&REV_01\3&11583659&0&D8
   Driver: n/a

     Name: Intel(R) 82945G Express Chipset Family
Device ID: PCI\VEN_8086&DEV_2772&SUBSYS_26331019&REV_02\3&11583659&0&10
   Driver: n/a

     Name: Intel(R) 82801G (ICH7 Family) USB2 Enhanced Host Controller - 27CC
Device ID: PCI\VEN_8086&DEV_27CC&SUBSYS_26331019&REV_01\3&11583659&0&EF
   Driver: n/a

     Name: Intel(R) 945G/GZ/GC/P/PL Processor to I/O Controller - 2770
Device ID: PCI\VEN_8086&DEV_2770&SUBSYS_26331019&REV_02\3&11583659&0&00
   Driver: n/a

     Name: Intel(R) 82801G (ICH7 Family) USB Universal Host Controller - 27CB
Device ID: PCI\VEN_8086&DEV_27CB&SUBSYS_26331019&REV_01\3&11583659&0&EB
   Driver: n/a

     Name: Intel(R) 82801 PCI Bridge - 244E
Device ID: PCI\VEN_8086&DEV_244E&SUBSYS_26331019&REV_E1\3&11583659&0&F0
   Driver: n/a

------------------
DirectShow Filters
------------------

DirectShow Filters:
WMAudio Decoder DMO,0x00800800,1,1,WMADMOD.DLL,6.01.7601.25734
WMAPro over S/PDIF DMO,0x00600800,1,1,WMADMOD.DLL,6.01.7601.25734
WMSpeech Decoder DMO,0x00600800,1,1,WMSPDMOD.DLL,6.01.7601.23403
MP3 Decoder DMO,0x00600800,1,1,mp3dmod.dll,6.01.7601.23403
Mpeg4s Decoder DMO,0x00800001,1,1,mp4sdecd.dll,6.01.7601.24559
WMV Screen decoder DMO,0x00600800,1,1,wmvsdecd.dll,6.01.7601.23403
WMVideo Decoder DMO,0x00800001,1,1,wmvdecod.dll,6.01.7601.25653
Mpeg43 Decoder DMO,0x00800001,1,1,mp43decd.dll,6.01.7601.23403
Mpeg4 Decoder DMO,0x00800001,1,1,mpg4decd.dll,6.01.7601.25682
DV Muxer,0x00400000,0,0,qdv.dll,6.06.7601.23403
Color Space Converter,0x00400001,1,1,quartz.dll,6.06.7601.24537
WM ASF Reader,0x00400000,0,0,qasf.dll,12.00.7601.23403
Screen Capture filter,0x00200000,0,1,wmpsrcwp.dll,12.00.7601.17514
AVI Splitter,0x00600000,1,1,quartz.dll,6.06.7601.24537
VGA 16 Color Ditherer,0x00400000,1,1,quartz.dll,6.06.7601.24537
SBE2MediaTypeProfile,0x00200000,0,0,sbe.dll,6.06.7601.23403
Microsoft DTV-DVD Video Decoder,0x005fffff,2,4,msmpeg2vdec.dll,12.00.9200.17037
AC3 Parser Filter,0x00600000,1,1,mpg2splt.ax,6.06.7601.24555
StreamBufferSink,0x00200000,0,0,sbe.dll,6.06.7601.23403
MJPEG Decompressor,0x00600000,1,1,quartz.dll,6.06.7601.24537
MPEG-I Stream Splitter,0x00600000,1,2,quartz.dll,6.06.7601.24537
SAMI (CC) Parser,0x00400000,1,1,quartz.dll,6.06.7601.24537
VBI Codec,0x00600000,1,4,VBICodec.ax,6.06.7601.23403
MPEG-2 Splitter,0x005fffff,1,0,mpg2splt.ax,6.06.7601.24555
Closed Captions Analysis Filter,0x00200000,2,5,cca.dll,6.06.7601.23403
SBE2FileScan,0x00200000,0,0,sbe.dll,6.06.7601.23403
Microsoft MPEG-2 Video Encoder,0x00200000,1,1,msmpeg2enc.dll,6.01.7601.23403
Internal Script Command Renderer,0x00800001,1,0,quartz.dll,6.06.7601.24537
MPEG Audio Decoder,0x03680001,1,1,quartz.dll,6.06.7601.24537
DV Splitter,0x00600000,1,2,qdv.dll,6.06.7601.23403
Video Mixing Renderer 9,0x00200000,1,0,quartz.dll,6.06.7601.24537
Microsoft MPEG-2 Encoder,0x00200000,2,1,msmpeg2enc.dll,6.01.7601.23403
ACM Wrapper,0x00600000,1,1,quartz.dll,6.06.7601.24537
Video Renderer,0x00800001,1,0,quartz.dll,6.06.7601.24537
MPEG-2 Video Stream Analyzer,0x00200000,0,0,sbe.dll,6.06.7601.23403
Line 21 Decoder,0x00600000,1,1,qdvd.dll,6.06.7601.24555
Video Port Manager,0x00600000,2,1,quartz.dll,6.06.7601.24537
Video Renderer,0x00400000,1,0,quartz.dll,6.06.7601.24537
VPS Decoder,0x00200000,0,0,WSTPager.ax,6.06.7601.23403
WM ASF Writer,0x00400000,0,0,qasf.dll,12.00.7601.23403
VBI Surface Allocator,0x00600000,1,1,vbisurf.ax,6.01.7601.23403
File writer,0x00200000,1,0,qcap.dll,6.06.7601.17514
iTV Data Sink,0x00600000,1,0,itvdata.dll,6.06.7601.17514
iTV Data Capture filter,0x00600000,1,1,itvdata.dll,6.06.7601.17514
DVD Navigator,0x00200000,0,3,qdvd.dll,6.06.7601.24555
Overlay Mixer2,0x00200000,1,1,qdvd.dll,6.06.7601.24555
AVI Draw,0x00600064,9,1,quartz.dll,6.06.7601.24537
RDP DShow Redirection Filter,0xffffffff,1,0,DShowRdpFilter.dll,
Microsoft MPEG-2 Audio Encoder,0x00200000,1,1,msmpeg2enc.dll,6.01.7601.23403
WST Pager,0x00200000,1,1,WSTPager.ax,6.06.7601.23403
MPEG-2 Demultiplexer,0x00600000,1,1,mpg2splt.ax,6.06.7601.24555
DV Video Decoder,0x00800000,1,1,qdv.dll,6.06.7601.23403
SampleGrabber,0x00200000,1,1,qedit.dll,6.06.7601.23403
Null Renderer,0x00200000,1,0,qedit.dll,6.06.7601.23403
MPEG-2 Sections and Tables,0x005fffff,1,0,Mpeg2Data.ax,6.06.7601.25854
Microsoft AC3 Encoder,0x00200000,1,1,msac3enc.dll,6.01.7601.23403
StreamBufferSource,0x00200000,0,0,sbe.dll,6.06.7601.23403
Smart Tee,0x00200000,1,2,qcap.dll,6.06.7601.17514
Overlay Mixer,0x00200000,0,0,qdvd.dll,6.06.7601.24555
AVI Decompressor,0x00600000,1,1,quartz.dll,6.06.7601.24537
AVI/WAV File Source,0x00400000,0,2,quartz.dll,6.06.7601.24537
Wave Parser,0x00400000,1,1,quartz.dll,6.06.7601.24537
MIDI Parser,0x00400000,1,1,quartz.dll,6.06.7601.24537
Multi-file Parser,0x00400000,1,1,quartz.dll,6.06.7601.24537
File stream renderer,0x00400000,1,1,quartz.dll,6.06.7601.24537
Microsoft DTV-DVD Audio Decoder,0x005fffff,1,1,msmpeg2adec.dll,6.01.7601.23285
StreamBufferSink2,0x00200000,0,0,sbe.dll,6.06.7601.23403
AVI Mux,0x00200000,1,0,qcap.dll,6.06.7601.17514
Line 21 Decoder 2,0x00600002,1,1,quartz.dll,6.06.7601.24537
File Source (Async.),0x00400000,0,1,quartz.dll,6.06.7601.24537
File Source (URL),0x00400000,0,1,quartz.dll,6.06.7601.24537
Infinite Pin Tee Filter,0x00200000,1,1,qcap.dll,6.06.7601.17514
Enhanced Video Renderer,0x00200000,1,0,evr.dll,6.01.7601.24499
BDA MPEG2 Transport Information Filter,0x00200000,2,0,psisrndr.ax,6.06.7601.25854
MPEG Video Decoder,0x40000001,1,1,quartz.dll,6.06.7601.24537

WDM Streaming Tee/Splitter Devices:
Conversor em T entre Coletores,0x00200000,1,1,ksproxy.ax,6.01.7601.23403

Video Compressors:
WMVideo8 Encoder DMO,0x00600800,1,1,wmvxencd.dll,6.01.7601.23403
WMVideo9 Encoder DMO,0x00600800,1,1,wmvencod.dll,6.01.7601.23403
MSScreen 9 encoder DMO,0x00600800,1,1,wmvsencd.dll,6.01.7601.23403
DV Video Encoder,0x00200000,0,0,qdv.dll,6.06.7601.23403
MJPEG Compressor,0x00200000,0,0,quartz.dll,6.06.7601.24537
Cinepak Codec by Radius,0x00200000,1,1,qcap.dll,6.06.7601.17514
Codec IYUV Intel,0x00200000,1,1,qcap.dll,6.06.7601.17514
Codec IYUV Intel,0x00200000,1,1,qcap.dll,6.06.7601.17514
Microsoft RLE,0x00200000,1,1,qcap.dll,6.06.7601.17514
Microsoft Video 1,0x00200000,1,1,qcap.dll,6.06.7601.17514

Audio Compressors:
WM Speech Encoder DMO,0x00600800,1,1,WMSPDMOE.DLL,6.01.7601.23403
WMAudio Encoder DMO,0x00600800,1,1,WMADMOE.DLL,6.01.7601.23403
IMA ADPCM,0x00200000,1,1,quartz.dll,6.06.7601.24537
PCM,0x00200000,1,1,quartz.dll,6.06.7601.24537
Microsoft ADPCM,0x00200000,1,1,quartz.dll,6.06.7601.24537
GSM 6.10,0x00200000,1,1,quartz.dll,6.06.7601.24537
CCITT A-Law,0x00200000,1,1,quartz.dll,6.06.7601.24537
CCITT u-Law,0x00200000,1,1,quartz.dll,6.06.7601.24537
MPEG Layer-3,0x00200000,1,1,quartz.dll,6.06.7601.24537

Audio Capture Sources:
Microfone (Dispositivo de High ,0x00200000,0,0,qcap.dll,6.06.7601.17514

PBDA CP Filters:
PBDA DTFilter,0x00600000,1,1,CPFilters.dll,6.06.7601.23403
PBDA ETFilter,0x00200000,0,0,CPFilters.dll,6.06.7601.23403
PBDA PTFilter,0x00200000,0,0,CPFilters.dll,6.06.7601.23403

Midi Renderers:
Default MidiOut Device,0x00800000,1,0,quartz.dll,6.06.7601.24537
Microsoft GS Wavetable Synth,0x00200000,1,0,quartz.dll,6.06.7601.24537

WDM Streaming Capture Devices:
Captura Mista de HD Audio,0x00200000,1,1,ksproxy.ax,6.01.7601.23403

WDM Streaming Rendering Devices:
Fone de Ouvido/Alto-falantes de HD Audio,0x00200000,1,1,ksproxy.ax,6.01.7601.23403
Saída de SPDIF de HD Audio,0x00200000,1,1,ksproxy.ax,6.01.7601.23403

BDA Network Providers:
Microsoft ATSC Network Provider,0x00200000,0,1,MSDvbNP.ax,6.06.7601.25854
Microsoft DVBC Network Provider,0x00200000,0,1,MSDvbNP.ax,6.06.7601.25854
Microsoft DVBS Network Provider,0x00200000,0,1,MSDvbNP.ax,6.06.7601.25854
Microsoft DVBT Network Provider,0x00200000,0,1,MSDvbNP.ax,6.06.7601.25854
Microsoft Network Provider,0x00200000,0,1,MSNP.ax,6.06.7601.25854

Multi-Instance Capable VBI Codecs:
VBI Codec,0x00600000,1,4,VBICodec.ax,6.06.7601.23403

BDA Transport Information Renderers:
BDA MPEG2 Transport Information Filter,0x00600000,2,0,psisrndr.ax,6.06.7601.25854
MPEG-2 Sections and Tables,0x00600000,1,0,Mpeg2Data.ax,6.06.7601.25854

BDA CP/CA Filters:
Decrypt/Tag,0x00600000,1,1,EncDec.dll,6.06.7601.25888
Encrypt/Tag,0x00200000,0,0,EncDec.dll,6.06.7601.25888
PTFilter,0x00200000,0,0,EncDec.dll,6.06.7601.25888
XDS Codec,0x00200000,0,0,EncDec.dll,6.06.7601.25888

WDM Streaming Communication Transforms:
Conversor em T entre Coletores,0x00200000,1,1,ksproxy.ax,6.01.7601.23403

Audio Renderers:
Alto-falantes (Dispositivo de H,0x00200000,1,0,quartz.dll,6.06.7601.24537
Default DirectSound Device,0x00800000,1,0,quartz.dll,6.06.7601.24537
Default WaveOut Device,0x00200000,1,0,quartz.dll,6.06.7601.24537
DirectSound: Alto-falantes (Dispositivo de High Definition Audio),0x00200000,1,0,quartz.dll,6.06.7601.24537
DirectSound: Áudio Digital (S/PDIF) (Dispositivo de High Definition Audio),0x00200000,1,0,quartz.dll,6.06.7601.24537
Áudio Digital (S/PDIF) (Disposi,0x00200000,1,0,quartz.dll,6.06.7601.24537

---------------
EVR Power Information
---------------
Current Setting: {5C67A112-A4C9-483F-B4A7-1D473BECAFDC} (Quality) 
  Quality Flags: 2576
    Enabled:
    Force throttling
    Allow half deinterlace
    Allow scaling
    Decode Power Usage: 100
  Balanced Flags: 1424
    Enabled:
    Force throttling
    Allow batching
    Force half deinterlace
    Force scaling
    Decode Power Usage: 50
  PowerFlags: 1424
    Enabled:
    Force throttling
    Allow batching
    Force half deinterlace
    Force scaling
    Decode Power Usage: 0

**Comment by nitrostemp** [comment]
yea it's due to your integrated gpu not supporting 3.3 which is required for OOOT

**Comment by Lufims** [comment]
> yea it's due to your integrated gpu not supporting 3.3 which is required for OOOT

ok then, sorry for the inconvenience
