### ISSUE TITLE
Mouse Camera Bug

### ISSUE THREAD

**Issue by zeldaking** [blawar/ooot#343]
I'm trying to use my mouse as like a camera like it said I could in the Wiki but it doesn't work and when I disable useClassicCamera in the config, when I relaunch the game it re-enables itself.

**Comment by frizzle101101** [comment]
Are you using the master branch?

**Comment by zeldaking** [comment]
No. I'm using the dev branch. I'll update to the master branch and see if it gets fixed.

**Comment by frizzle101101** [comment]
Try my Pull request: Dev which is my branch that will be most useful, master is really bare bones for mouse support
