### ISSUE TITLE
Crash after beating ghoma

### ISSUE THREAD

**Issue by topkeksphagetti** [blawar/ooot#35]
![image](https://user-images.githubusercontent.com/15426253/152040226-abf91120-ef4a-464c-82f9-a375fb53ae75.png)

**Comment by DaMarkov** [comment]
I can confirm this issue. The crash happens in gDPFullSync() in gDP.cpp of GLideN64.

REG.MI_INTR points to invalid memory so that on line 1010 *REG.MI_INTR |= MI_INTR_DP; causes an illegal write access.

**Comment by blawar** [comment]
@DaMarkov REG.MI_INTR is being corrupted right before the crash by heap corruption from UnswapCopyWrap() being called from gDPLoadBlock.  The display list being executed is from D_80009320 which appears to be non-decompiled display list, and there are likely segment and pointer references to be patched:

https://github.com/blawar/ooot/blob/master/src/port/rsp_boot.c#L3

![image](https://user-images.githubusercontent.com/10227949/152654405-64b1fa63-d125-4dca-8f3a-07da98ba3890.png)

**Comment by blawar** [comment]
fixed

**Comment by DaMarkov** [comment]
Are you sure this is fixed? I did `git pull`, recompiled GLideN64 and also OOT, but the game still crashes.
It looks like it crashes about 5 seconds later than before.
Did I do something wrong?

![2022-02-05 22-45-17 (3)](https://user-images.githubusercontent.com/35939509/152660941-c4caf9c2-5b2a-490c-be4d-ebe6f58d0203.gif)
.
