### ISSUE TITLE
Treasure chest glow missing when opening a chest

### ISSUE THREAD

**Issue by Maattoo** [blawar/ooot#36]
Whenever you open a big chest, the glow effect doesnt appear.

![noglow](https://user-images.githubusercontent.com/98851375/152054754-0bc7d8e7-5471-4d6e-a8b5-8d6e6d970e3c.png)

**Comment by Zero3K** [comment]
This might be caused by frame buffer emulation not being used.

**Comment by DaMarkov** [comment]
Tested with frame buffer emulation.
Bug is not fixed.

**Comment by blawar** [comment]
fixed
