### ISSUE TITLE
Green Background When Paused

### ISSUE THREAD

**Issue by MrEveryDay98** [blawar/ooot#37]
![image](https://user-images.githubusercontent.com/98854338/152063720-823827e5-b1eb-48f7-88cd-ffb3e741d7df.png)

**Comment by blawar** [comment]
This is caused by frame buffer emulation not being enabled.  Keeping this open until FBE is implemented.

**Comment by Zero3K** [comment]
I think this is a duplicate of #7.

**Comment by Zero3K** [comment]
It has been fixed thanks to commit https://github.com/blawar/ooot/commit/ac2b25f6a5030a23867a68e989b104c2af11d340.
