### ISSUE TITLE
Crash after castle grounds Malon text

### ISSUE THREAD

**Issue by ungaDamage** [blawar/ooot#38]
https://user-images.githubusercontent.com/98857629/152073528-cc03791b-4ce8-4163-b80e-396262536d35.mp4

**Comment by ungaDamage** [comment]
Also crashes in town
https://user-images.githubusercontent.com/98857629/152075078-0c0fb633-b6d7-4626-8ddf-e806eeb4376b.mp4

**Comment by blawar** [comment]
Can you reproduce with master?  I was unable to reproduce, and a similar bug was fixed.

**Comment by Zero3K** [comment]
That bug is #41.

**Comment by DaMarkov** [comment]
The crash has been fixed. The text is still messed up, but we have this in a lot of places, so I think this issue can be closed

https://user-images.githubusercontent.com/35939509/152687179-aadc1c01-47cb-4f00-8c1d-4141cc545de2.mp4

.

**Comment by blawar** [comment]
@DaMarkov try pulling in master that I just commited.  you will have to re-run this after:

```
tools\msgenc.py assets\text\charmap.txt assets\text\message_data.h build\assets\text\message_data.enc.h
tools\msgenc.py assets\text\charmap.txt assets\text\message_data_staff.h build\assets\text\message_data_staff.enc.h
```

**Comment by DaMarkov** [comment]
Thanks. The text glitch is also fixed. This issue can be closed.
