### ISSUE TITLE
Link's Model Doesn't Appear in The Equipment Screen

### ISSUE THREAD

**Issue by MatttyMattHew** [blawar/ooot#4]
![image](https://user-images.githubusercontent.com/98795913/151915198-a1af9d2e-08ae-46c8-9208-7d363add8ffa.png)

**Comment by DaMarkov** [comment]
This is due to framebuffer emulation being disabled.
Will be fixed in an upcoming PR.
![image](https://user-images.githubusercontent.com/35939509/152914899-df6ddce0-987a-4505-95e2-9d0ab9715f7c.png)

**Comment by Zero3K** [comment]
It has been fixed thanks to commit https://github.com/blawar/ooot/commit/ac2b25f6a5030a23867a68e989b104c2af11d340.
