### ISSUE TITLE
Softlock: lost woods ocarina minigame

### ISSUE THREAD

**Issue by ungaDamage** [blawar/ooot#43]
Ocarina minigame in lost woods softlocks the game.
https://user-images.githubusercontent.com/98857629/152091942-24d6b187-d990-44ee-b920-b8167bdb4b9a.mp4

**Comment by blawar** [comment]
I believe this is caused by no sound, there was a similar issue whenever a song is played on the ocarina.  I suspect the timing of the audio is used to trigger events.  Holding open.
