### ISSUE TITLE
Discord links in README are expired or invalid

### ISSUE THREAD

**Issue by c0d3h4x0r** [blawar/ooot#46]
The links need to be updated with permanently-valid invitation links for the Discord server.

**Comment by DaBanana64** [comment]
The server got deleted.

**Comment by OCASM** [comment]
The hate mob got them.

**Comment by jdroo** [comment]
good to know I was not banned. Will the server be coming back?

**Comment by OCASM** [comment]
@blawar just updated the link:

https://discord.com/invite/8tktBEhbZm

**Comment by blawar** [comment]
fixed
