### ISSUE TITLE
no black fadeout when using doors or warps 

### ISSUE THREAD

**Issue by numbypad** [blawar/ooot#51]
when going through house doors or any of the warps there is no black fade out then fade in

**Comment by DaMarkov** [comment]
Is there a specific doors to test this with?
I turned on framebuffer emulation and got this result.
Looks good to me, so maybe this is another framebuffer emulation issue.

https://user-images.githubusercontent.com/35939509/152918663-2a5a3f5c-bfee-4c5e-bd25-8875a14a63ee.mp4

**Comment by Zero3K** [comment]
It has been fixed thanks to commit https://github.com/blawar/ooot/commit/ac2b25f6a5030a23867a68e989b104c2af11d340.
