### ISSUE TITLE
Golden Skulltula Token Icon on Kokiri Forest map

### ISSUE THREAD

**Issue by Detrimantix** [blawar/ooot#54]
Golden skulltula Token Icon on Kokiri Forest map is visible without acquiring any golden skulltulas.

![image](https://user-images.githubusercontent.com/99096248/152656735-2aee8842-41fe-4d6a-a968-6da8802cd6bb.png)

**Comment by blawar** [comment]
Is this bug still on master?  I am unable to reproduce.

**Comment by Wesley107772** [comment]
Seems to be fixed now. Related to this issue was the skulltulas not appearing at all in Kokiri Forest, but now they appear as usual again

**Comment by DaMarkov** [comment]
Turns out this "bug" is a feature of the debug version.
This also happens on an emulator. Unfortunately, I couldn't find it anywhere documented.
