### ISSUE TITLE
Broken animation when strafing right as adult link

### ISSUE THREAD

**Issue by wowjinxy** [blawar/ooot#56]

**Comment by Chewbear67** [comment]
Also broken for kid Link I believe

**Comment by GreenSwede** [comment]
mrneo240 has a fix for this on his local branch but it hasn't been committed yet.

**Comment by mrneo240** [comment]
> mrneo240 has a fix for this on his local branch but it hasn't been committed yet.

I have to figure out what the fix was again. I mentioned it previously but I've now forgotten

**Comment by DaMarkov** [comment]
Can confirm this has been fixed with the recent commits.
