### ISSUE TITLE
message_data_staff and message_data part of repo?

### ISSUE THREAD

**Issue by HungryBananaSalad** [blawar/ooot#59]
Hi, it looks like the following files are tracked in the repository:

https://github.com/blawar/ooot/blob/a0c4bc5764c2cb9dc47044ffbba581ec2b095ab7/assets/text/message_data_staff.h
https://github.com/blawar/ooot/blob/a0c4bc5764c2cb9dc47044ffbba581ec2b095ab7/assets/text/message_data.h

Shouldn't they be extracted from the baserom instead by every user?

**Comment by mrneo240** [comment]
seems so based on zeldaret/oot
could use these (very scary) commands:
```
git filter-branch --index-filter  'git rm -rf --cached --ignore-unmatch assets/text/message_data.h' HEAD
git filter-branch --index-filter  'git rm -rf --cached --ignore-unmatch assets/text/message_data_staff.h' HEAD
git push origin --force --all
```

**Comment by Zero3K** [comment]
fatal: ambiguous argument 'rm': unknown revision or path not in the working tree

**Comment by Zero3K** [comment]
And it results in an empty file when I deleted them manually and re-ran setup_assets.bat.

**Comment by HungryBananaSalad** [comment]
The extract_assets.py always errors out when trying to extract the assets with multiprocessing for me in addition to not being able to get the text extracted

**Comment by Zero3K** [comment]
Replace the msg py scripts in .\tools with the ones in this archive in order to fix it:

[msg.zip](https://github.com/blawar/ooot/files/8010765/msg.zip)

**Comment by HungryBananaSalad** [comment]
I just did a new pull and saw that the fix was provided 2h ago for the text extraction

**Comment by Zero3K** [comment]
I removed them.
