### ISSUE TITLE
Sunset Texture Has a Line at The Top

### ISSUE THREAD

**Issue by MatttyMattHew** [blawar/ooot#6]
![image](https://user-images.githubusercontent.com/98795913/151915579-26224a38-1e52-4c04-a911-1920f14bdbec.png)

**Comment by mrneo240** [comment]
Sun texture is described incorrectly in original rom will need patch mid extraction

**Comment by Jj0YzL5nvJ** [comment]
https://github.com/gonetz/GLideN64/issues/2124#issuecomment-560347427

> These textures have different formats. 4-1 is 8bit IM_FMT_I (intensity), while 3-0 is 4bit IM_FMT_IA (intensity-alpha). They can be visually the same, but they are different.

**Comment by DaMarkov** [comment]
mrneo is correct. `gameplay_keep_unaccounted_04D140` should be part of `gSunEvening3Tex`.
The bytes from `gameplay_keep_unaccounted_04D140` belong to the end of the texture.
I suggest to add the bytes when extracting the asset and getting rid of `gameplay_keep_unaccounted_04D140`.

**Comment by mrneo240** [comment]
Good luck lol. 
Zapd depends on gfxd which both are fucked because the game has is it incorrect in the cartridge. Think Mario smoke.

**Comment by DaMarkov** [comment]
Fixed in PR #201.
@mrneo240 I was actually very easy. I just had to shower twice, because I felt so dirty reading that Python code.
