### ISSUE TITLE
Anju(chicken lady) is missing in kakariko as child

### ISSUE THREAD

**Issue by numbypad** [blawar/ooot#64]
New file, after beating deku tree I went to kak to collect the cuccos for the bottle, but Anju who usually stands right beside the fence you throw the chickens in is missing lol.

**Comment by DaMarkov** [comment]
An easy way to reproduce: Select the first save slot, choose `2: SPOT01` and walk up to the corner where Anju is supposed to be.

**Comment by DaMarkov** [comment]
Relevant code is in `EnNiwLady_Init()`
```
this->objectOsAnimeIndex = Object_GetIndex(&globalCtx->objectCtx, OBJECT_OS_ANIME);
    if ((this->objectOsAnimeIndex < 0) || (this->objectAneIndex < 0)) {
        Actor_Kill(thisx);
        return;
    }
```

`Object_GetIndex` returns a `s32` when cast to `s8` `objectOsAnimeIndex ` becomes negative and the actor get killed.

PR #69 fixes this issue.

**Comment by Zero3K** [comment]
PR #69 has been merged so this issue is now being closed.
