### ISSUE TITLE
Pause Screen Background Isn't Transparent

### ISSUE THREAD

**Issue by MatttyMattHew** [blawar/ooot#7]
![image](https://user-images.githubusercontent.com/98795913/151915647-9d4d0d3b-1da9-4616-a1be-260d930e91bd.png)

**Comment by DaMarkov** [comment]
This is due to framebuffer emulation being disabled.
Will be fixed in an upcoming PR.
![image](https://user-images.githubusercontent.com/35939509/152914516-d2263900-9864-41ca-bb18-682c494f467a.png)

**Comment by Zero3K** [comment]
It has been fixed thanks to commit https://github.com/blawar/ooot/commit/ac2b25f6a5030a23867a68e989b104c2af11d340.
