### ISSUE TITLE
Softlock when learning new songs

### ISSUE THREAD

**Issue by Chewbear67** [blawar/ooot#74]
When learning Zelda's lullaby or Saria's song, it was impossible to play the displayed keys. The only way to get out of playing was opening up Navi's prompt, which glitched the game until you talked to someone. This would allow you to play the song after, but it's a very buggy operation.

The glitch was NOT escapable when learning Epona's song, as Navi had no prompt to give. This left me with no options but to close the game.

**Comment by Zero3K** [comment]
This is because audio is currently not supported. It will be fixed when it is.

**Comment by mrneo240** [comment]
Can you offer a save with this situation close by?

**Comment by Dewey-Wilkerson** [comment]
> Can you offer a save with this situation close by?

In Map Select, go to the Treasure Chest Room (Number 119), and the Ocarina of Time is right by the entrance, on the left hand side; picking it up will trigger the Song of Time cutscene, which will softlock you in this manner.

**Comment by blawar** [comment]
can you test this with the audio branch?

**Comment by Wesley107772** [comment]
Seems to be fixed in the audio branch. Tested with sun's song, song of storms, minuet of forest and bolero of fire, each one works as expected.
