### ISSUE TITLE
Quest Status Menu Has Visible Seams

### ISSUE THREAD

**Issue by MatttyMattHew** [blawar/ooot#8]
![image](https://user-images.githubusercontent.com/98795913/151915717-6cd44e86-1538-45c7-ba00-8fe2c54ebf43.png)

**Comment by DaMarkov** [comment]
Looks close to this screenshot from Project64.
Is there any difference I am missing?
![GLideN64_THE_LEGEND_OF_ZELDA_000](https://user-images.githubusercontent.com/35939509/153073027-dd80b735-1c56-4292-92cb-6a71f81c0a52.png)

**Comment by GreenSwede** [comment]
> Looks close to this screenshot from Project64. Is there any difference I am missing? ![GLideN64_THE_LEGEND_OF_ZELDA_000](https://user-images.githubusercontent.com/35939509/153073027-dd80b735-1c56-4292-92cb-6a71f81c0a52.png)
On N64 (and on other graphics plugins I think for emulators) there are no visible seams.
![153073027-dd80b735-1c56-4292-92cb-6a71f81c0a52~2](https://user-images.githubusercontent.com/42186507/153074550-feafab70-6435-45ca-b7ad-6905516f9693.png)

**Comment by GreenSwede** [comment]
![frP7gtE](https://user-images.githubusercontent.com/42186507/153075700-3d501100-4fd3-4775-8968-82927f837773.png)

**Comment by Zelllll** [comment]
Three-point filtering doesn't actually fix this issue, this is really just a consequence of upscaling I think. This issue is probably possible to see on N64 as well, just not noticeable.

**Comment by Zelllll** [comment]
Closing this for now since fixing this falls under enhancement territory.
