### ISSUE TITLE
Crash in graveyard after suns song as child

### ISSUE THREAD

**Issue by numbypad** [blawar/ooot#81]
After going into the royale tomb while it was daylight and attempting to learn the suns song(which currently soft locks, but that issue is already open) you can skip this scene to advance to the cutscene where time changes, (though you still won't learn the song.) After doing this and exiting the tomb back to the graveyard which is now Night due to the suns song, the game crashes with this error.
![error](https://user-images.githubusercontent.com/89367228/152743647-f3bcb7f3-2356-4ba5-9bc3-534928257ed7.png)

**Comment by Wesley107772** [comment]
The error is related to Dampé, I believe more specifically his default head rotation when the player is not in range.
Debugger points to line 573 in src\overlays\actors\ovl_En_Tk\z_en_tk.c, which mentions v1 not being initialized. There's already a comment in the code about this bug.
I'm not really a programmer, but simply changing line 532 to "s16 v1 = 0;" seems to have fixed it for me with no immediately visible oddities.

Quick note, I haven't tested it on the audio branch but I feel like it's a separate issue either way
![image](https://user-images.githubusercontent.com/88684291/153354798-173fb0bf-7014-4b7e-a976-0dbed8a5d75f.png)

**Comment by blawar** [comment]
Thank you for finding the issue wesley @Wesley107772 , this is actually an original bug from the game, see: https://github.com/blawar/ooot/commit/27ab287584a843a01dc395396f4408786631ce11
