### ISSUE TITLE
Smoke Clouds wrong position over volcano

### ISSUE THREAD

**Issue by mrneo240** [blawar/ooot#88]
Smoke is circling wrong position, likely due to scaling/aspect
![2022-02-08_11-23](https://user-images.githubusercontent.com/819028/153030379-2991eb43-134c-41b0-9dcd-1da87378af4c.png)

## Expected Behavior
Clouds go left 

## Possible Solution
scale with aspect

## Steps to Reproduce
1. go to temple of time warp from debug menu
2. exit

**Comment by DaMarkov** [comment]
Moved clouds left d71b6ce228f22d5ece6d2f6deb713f84d83e69d0
