### ISSUE TITLE
Bow + Arrow Icons Missing in Inventory

### ISSUE THREAD

**Issue by MatttyMattHew** [blawar/ooot#9]
Edit: Appears as Adult Link.

![image](https://user-images.githubusercontent.com/98795913/151915941-d4f7ea7e-cf1d-4cbe-9f21-190fd06dd75e.png)

**Comment by DaMarkov** [comment]
Already fixed, can be closed
![image](https://user-images.githubusercontent.com/35939509/153194032-5e8b2c8c-93ac-4a82-ad9e-bb01773b1b4a.png)
