### ISSUE TITLE
Adult Link causes a crash

### ISSUE THREAD

**Issue by DaMarkov** [blawar/ooot#93]
The most recent commits cause an array out of range exception.

## Current Behavior
Game crashes in Hyrule and Kakriko village as Adult Link.

## Expected Behavior
Game didn't crash a few commits before.

## Steps to Reproduce

1. git checkout 8185f70634533d22664ce2698c8443b2e5a8dc45
2. Compile OOT.sln
3. Choose save slot 1
4. Press B to choose Adult Link. Select Hyrule or Kakariko and press A

**Comment by DaMarkov** [comment]
The cause is https://github.com/blawar/ooot/commit/8185f70634533d22664ce2698c8443b2e5a8dc45
```
dList = dLists[sDListsLodOffset+dListOffset];
*dList = dLists[sDListsLodOffset];
```
The first line was added. `sDListsLodOffset` is 0 and `dListOffset` is 1 when the crash happened.
`dList` is set to NULL, which causes a crash in the second line.

@[mrneo240](https://github.com/blawar/ooot/commits?author=mrneo240) was this intended to be
`*dList = dLists[sDListsLodOffset+dListOffset];`

**Comment by blawar** [comment]
fixed
